# Bipolär sjukdom

## Inledning

Vad är det.

Teorier om patofysiologi. Ärftlighet. Livshändelser kan vara utlösande.

Epidemiologi. Beskriv andel av tiden i mani/depression.

Samsjuklighet/riskbeteenden.

Prognos.

## Diagnostik

Huvudkriteriet för diagnosen bipolär sjukdom är förekomst av mani (vid typ I) eller hypomani (vid typ II). Episoder med depression är inte obligat, men vanligt, och särskilt framträdande vid typ II.

En manisk episod innebär att stämningsläget är förhöjt, _expansivt_ eller irritabelt tillsammans med ökad energi eller _målinriktad aktivitet_.

För att betraktas som en manisk episod krävs att förändringen i stämningsläge och aktivitet är ihållande (föreligger nästan varje dag och större delen av dagen) under en tydligt avgränsad period (dvs inte ett varaktigt beteende) som varar minst en vecka. Om besvären är så påtagliga att de leder till sjukhusinläggning kan perioden dock vara kortare (ingen nedre gräns) och ändå räknas som en manisk episod.

Dessutom krävs att tre eller fler av följande symtom föreligger (samtidigt som förändringen i stämningsläge och -aktivitet): Uppblåst självförtroende eller _grandiositet_; minskat sömnbehov; ökad pratsamhet; _tankeflykt_ eller en känsla av att tankarna rusar; distraherbarhet (av yttre ovidkommande stimuli); ökat målinriktat beteende (tex på arbete, skola, socialt, sexuellt) eller psykomotorisk agitation; överdrivet högriskbeteende (tex ekonomiskt, sexuellt). 

Blandad episod av mani med samtidiga depressiva inslag förekommer. Vid sådan episod är dysfori, ångest, skuldkänslor, suicidtankar och irritabilitet vanligare medan man vid ren manisk episod oftare observerat grandiositet, eufori och talträngdhet [@Cassidy1998].

Vid hypomani saknas uttalad nedsättning av social funktion eller arbetsförmåga. Minsta varaktigheten är då fyra dagar. Om psykotiska symtom föreligger eller om symtomen leder till sjukhusinläggning räknas episoden som mani. Beteendet skall inte förklaras bättre av psykossjukdom eller vara en effekt av droger.

Diagnosen bipolär sjukdom typ I kan ställas om personen haft en eller flera maniska episoder under sin livstid, oavsett om depressiva episoder förekommit. Om hypomani förkommit men aldrig mani, samt minst en depression, ställs diagnosen bipolär sjukdom typ II.

Notera att snabba växlingar i humöret kan förekomma (tex mellan dysfori, eufori och irritabilitet). Ökat målinriktat beteende består ofta i överdrivet planerande av- och deltagande i flera aktiviteter, exempelvis vidlyftiga projekt inom områden där personen saknar specifik kompetens. Minskat sömnbehov innebär att personen känner sig utvilad trots minskad sömntid. Uppblåst självförtroende kan vara av vanföreställningskaraktär.

Förekomsten av olika symtom hos personer med bipolär diagnos som vårdas inneliggande i samband med en manisk eller blandad episod visas i **Tabell \@ref(tab:bipolar-symptoms)**. Uppsnabbat tal är karakteristiskt.

```{r bipolar-symptoms} 

tmp <- read_csv('bipolar-symptoms.csv')
cnames <- tmp$symptom
labs <- cnames
names(labs) <- fix.names(cnames)

tmp <- as_tibble(cbind(study = names(tmp), t(tmp)))
colnames(tmp) <- fix.names(c("study", cnames) )
tmp <- tmp[-1,]
tmp[5:ncol(tmp)] <- sapply(tmp[5:ncol(tmp)], as.numeric)
tmp%>%gather(symptom, percent, -c(study, ref, n, rigorous, type)) -> tmp ## long

tmp%>%
    mutate(
        n_symptom = n * percent/100,
        n_without = n - n_symptom
    )%>%filter(rigorous == "no")%>%
    group_by(ref, symptom)%>%
    summarise(
        n_total = sum(n),
        n_symptom = sum(n_symptom, na.omit = TRUE)
    )%>%
    filter(!is.na(n_symptom))-> tmp

tmp%>%
    group_by(symptom)%>%
    summarise(
        n = sum(n_total),
        n_symptom = sum(n_symptom)
    )%>%
    mutate(
        percent = n_symptom/n*100
    )%>%
    arrange(-percent)%>%
    mutate(
        percent = as.character(signif(percent, digits = 2))
               ) -> tmp
tmp%>%
    select(symptom, percent) -> tbl

## label table
## tbl$symptom <- query_label(tbl$symptom, labs) ## internal names
## names(tbl) <- c("Symptom", "Percent")
tbl$symptom <- query_label(tbl$symptom, varnames)
names(tbl) <- query_label(names(tbl), varnames)

x <- tbl

foot <- paste0("Resultaten är summerade från tre olika studier där respektive symtom efterfrågades vid totalt ", min(tmp$n), " till ", max(tmp$n), " bipolära episoder beroende på vilka studier som inkluderade kartläggning av symtomet.")

kable(x, "latex",
      align = c("l", rep('c', times = ncol(x))),
      caption = "Symtom vid bipolär episod av manisk eller blandad typ",
      booktabs=TRUE,
      escape=FALSE
      )%>%
    footnote(
        general= make_rows(foot),
        general_title = "",
        ##footnote_as_chunk=TRUE, 
        escape=FALSE) 



## ref [@Cassidy1998], aggregate of this and two other studies summarised in the same paper. Mixed and manic episodes aggregated.
## TODO: Översätt symtomen


``` 

_Exempel_

### Manisk episod, diagnoskriterier enligt DSM-5

> A. A distinct period of abnormally and persistently elevated, expansive, or irritable mood and abnormally and persistently increased goal-directed activity or energy, lasting at least 1 week and present most of the day, nearly every day (or any duration if hospitalization is necessary).

> B. During the period of mood disturbance and increased energy or activity, three (or more) of the following symptoms (four if the mood is only irritable) are present to a significant degree and represent a noticeable change from usual behavior:

> 1. Inflated self-esteem or grandiosity.

> 2. Decreased need for sleep (e.g., feels rested after only 3 hours of sleep).

> 3. More talkative than usual or pressure to keep talking.

> 4. Flight of ideas or subjective experience that thoughts are racing.

> 5. Distractibility (i.e., attention too easily drawn to unimportant or irrelevant external stimuli), as reported or observed.

> 6. Increase in goal-directed activity (either socially, at work or school, or sexually) or psychomotor agitation (i.e., puoseless non-goal-directed activity).

> 7. Excessive involvement in activities that have a high potential for painful consequences (e.g., engaging in unrestrained buying sprees, sexual indiscretions, or foolish business investments).

> C. The mood disturbance is sufficiently severe to cause marked impairment in social or occupational functioning or to necessitate hospitalization to prevent harm to self or others, or there are psychotic features.

> D. The episode is not attributable to the physiological effects of a substance (e.g., a drug of abuse, a medication, other treatment) or to another medical condition.

Note: A full manic episode that emerges during antidepressant treatment (e.g., medication, electroconvulsive therapy) but persists at a fully syndromal level beyond the physiological effect of that treatment is sufficient evidence for a manic episode and, therefore, a bipolar I diagnosis.

Note: Criteria A-D constitute a manic episode. At least one lifetime manic episode is required for the diagnosis of bipolar I disorder.


## Behandling

Snabbt isättande av behandling kan motiveras av att maniska perioder kan påverka hjärnan [@Abé2015].

Diskutera antidepressivas roll. Relatera till tid i mani/depression?

## Skattningsinstrument

Miller CJ, Johnson SL, Eisner L Assessment Tools for Adult Bipolar Disorder. Clin Psychol (New York). 2009 Jun; 16:(2)188-201

### HCL-32

Hypomania checklist (HCL 32): Medelvärdet högre vid bipolär sjukdom. Fråga 3 kan användas för cut-off: Mer än 13 p på den frågan indikerar bipolär sjukdom.

Ej tillräckligt effektivt för befolkningsscreening (icke-klinisk population) [@Lee2016].

"The HCL-32 showed an adequate discrimination power for distinguishing individuals with BDs from those with major depressive disorders in previous studies [6–9]. Those studies also identified two or three sub-domains of the scale representing separate clinical factors. Compared to the MDQ, the HCL-32 showed higher sensitivity and lower specificity in screening hypomania, having high accuracy for the detection of ‘softer’ BD cases [10]. However, both questionnaires were developed for and have been applied to patients in a depressive episode." [@Lee2016]

Investigation of the clinical utility of the hypomania checklist 32 (HCL-32) for the screening of bipolar disorders in the non-clinical adult population [@Lee2016]

Skalor för neuropsykiatriska besvär och tvång: http://www.memogen.se/tests.html

## Resources

Mood Disorders A Handbook Of Science And Practice, https://epdf.tips/mood-disorders-a-handbook-of-science-and-practice.html
