# Rättspsykiatri {#rattspsykiatri}

## Inledning

Ett allvarligt brott som begås under inverkan av en allvarlig psykisk störning _kan_ ge fängelseförbud (BrB 30 kap. 6 §) och påföljden rättspsykiatrisk vård (BrB 31 kap. 3 §).

Förloppet vid rättspsykiatrisk vård börjar när någon efter en gärning blir gripen och domstolen anser att den brottsmisstänktes psykiska tillstånd bör undersökas och därför begär en paragraf 7-undersökning (sk "p-sjua", "liten sinnesundersökning", se avsnitt \@ref(paragraf-sju)). Undersökningen görs vanligen på häktet, vid ett tillfälle, varefter ett intyg utfärdas. Med stöd av detta avgör domstolen om en rättspsykiatrisk undersökning (sk RPU) skall göras efter att skuldfrågan avgjorts. En sådan undersökning sker under vistelse på rättspsykiatrisk utredningsenhet. Därefter avkunnas en dom som kan ha påföljden rättspsykiatrisk vård.

Vid sidan om detta finns psykiatrisk vård inom kriminalvården. Anstalterna skall kunna erbjuda vård motsvarande psykiatrisk öppenvård. En intagen kan också vårdas inom rättspsykiatrin eller allmänpsykiatrin vid behov av slutenvård.

<!-- TODO: Länka till de avsnitt om olika faserna nedan -->

## Förkortningar

RPU, Rättspsykiatrisk utredning. Görs av rättspsykiater vid rättsmedicinalverket.

LRV, Lagen om rättspsykiatrisk vård.

BrB, Brottsbalken.

APS, Allvarlig psykisk störning.

SUP, Särskild utskrivningsprövning.

RPV, Rättspsykiatrisk vård.


## Grundläggande principer

Enligt straffrätten kräver brott att uppsåt finns (BrB 1 kap § 2). Påföljder i brottsbalken är böter, fängelse, villkorlig dom, skyddstillsyn, och överlämnande till särskild vård (BrB 1 kap § 3). 

Straff innebär att ett händelseförlopp av staten ges en moralisk mening. Det motiveras av prevention (behandling, avskräckning, inkapacitering) och vedergällning (rättvisa, proportionalitet till gärningens allvar och förövarens skuld, hämnd). Olika rättsliga teorier kan anse att straffet i sig har ett egenvärde (sk absoluta teorier eller vedergällningsteorier) eller betona den preventiva effekten av straffet (sk relativa teorier).

Begreppet ansvar är grundläggande inom rättspsykiatrisk vård. I Sverige anses man vara ansvarig för sin gärning och döms till påföljden rättspsykiatrisk vård. Vården man döms till är en slags straff varigenom man skall "sona sin gärning". Den juridiska särbehandlingen rör således påföljden av ett brott som man anses ansvarig för. De flesta andra länder har istället juridisk särbehandling i själva ansvarsfrågan, i USA tex "not guilty by reasons of insanity". I dessa länder placeras man dock trots ansvarsfrihet genom en administrativ dom på ett "high security hospital".

LRV kan ses som en avgränsing av personens relativa mänskliga rättigheter (skydd mot frihetsberövande; privatliv; skydd mot påtvingade kroppsliga ingrepp såsom besiktning, provtagning, undersökning, och sjukvård i allmän bemärkelse), vilket kan motiveras av den dömdes rätt till hälsa men även skyddandet av _andra_ personers hälsa. Det är alltså inte enbart är den dömdes rättigheter som vägs in i den etiska motiveringen av LRV. En etisk princip som vanligen tillämpas (i juridiken?) är att rätten till hälsa övertrumfar rätten till frihet.


## Akut rättspsykiatrisk vård

Förutom de fall där en person dömts till rättspsykiatrisk vård bedrivs sådan vård även även när en person som är anhållen, häktad eller intagen på kriminalvårdsanstalt behöver psykiatrisk vård som inte kan tillgodoses där personen är frihetsberövad. 

Sådan vård kan bedrivas på frivillig grund (enligt HSL) eller genom tvångsvård. För tvångsvård skrivs ett vårdintyg enligt LRV 5 § och rutan 2b används istället för rutan 2a i blanketten. Därmed behöver det i sådana fall inte finnas ett oundgängligt behov av vård. Övriga kriterier för psykiatrisk tvångsvård (APS och att personen motsätter sig vård) behöver vara uppfyllda. Om personen redan vårdas inneliggande enligt HSL kan intagningsbeslut fattas utan föregående vårdintyg (LRV 5 §)<!-- Eftersom personen redan är frihetsberövad - vi är en slags frihetsberövande -->. Vid pågående vård enligt LPT övergår vården automatiskt till LRV (LRV 4 §). Om intagningsbeslut ännu ej fattats görs det med det aktuella vårdintyget (något nytt behöver ej göras).<!-- Om vårdintyg skrivits men intagningsbeslut ej fattats och personen blir häktad, enligt vilken paragraf skall då intagningsbeslutet fattas? -->

Akut tvångsvård enligt LRV upphör omedelbart när frihetsberövandet upphör (§15 LRV). Detta gäller även tvångsvård där vårdintyg och intagningsbeslut gjorts. Då görs en LPT 14 § bedömning av chefsöverläkaren, där intagningsbeslut kan fattas utan föregående vårdintyg, och utan att farlighetskriteriet behöver vara uppfyllt (de vanliga kriterierna för LPT gäller). När det gäller tidsfrister för ansökan till förvaltningsrätten motsvarar detta LPT 11 § (konvertering).

Kriminalvården beslutar om säkerheten för den som är anhållen, häktad eller intagen på kriminalvårdsanstalt. Alternativen blir då: Vård på den plats där personen är frihetsberövad, allmänpsykiatrisk avdelning med häktespersonal på plats, flytt till rättspsykiatrisk avdelning, eller öppenvård med vistelse i häktet.

## Paragraf 7-undersökning {#paragraf-sju}

När domstolen anser att en brottsmisstänkt persons psykiska tillstånd bör undersökas begär den oftast en paragraf 7-undersökning, främst för att bedöma om det finns behov av att gå vidare med en rättspsykiatrisk undersökning. "Paragraf 7" syftar till 7 § lagen (1991:2041) om särskild personutredning i brottmål.

Domstolen kan även begära en typ av paragraf 7-undersökning som kallas paragraf 7-vård. Vid en sådan undersökning ska läkaren även bedöma om det finns förutsättningar för domstolen att döma den misstänkte till rättspsykiatrisk vård utan särskild utskrivningsprövning.

Paragraf 7-undersökningar kan även utföras när en brottsmisstänkt inte är häktad. Den misstänkte som ska undersökas blir då kallad till samtal med undersökningsläkaren. Om personen inte kommer på undersökningen trots flera kallelser kan hen bli hämtad till undersökningen av polis. När undersökningssamtalet är färdigt blir personen släppt på fri fot.

Fråga: Vem kan göra en paragraf 7-undersökning? Svar: En specialist i psykiatri som genomgått utbildning på rättsmedicinalverket. 

I vissa fall kan rätten begära en sk "vård-sjua". Personen kan då efter en paragraf 7-undersökning dömas till rättspsykiatrisk vård utan SUP, utan att någon RPU görs. I intyget kan läkaren då rekommendera rättspsykiatrisk vård utan SUP. Detta gäller vanligen personer som är välkända inom psykiatrin, med kronisk psykisk sjukdom, där en RPU inte bedöms tillföra någonting. Alternativt kan läkaren rekommendera att en RPU görs.

Se [rättsmedicinalverkets webbplats.](https://www.rmv.se/verksamheter/rattspsykiatri/paragraf-7-undersokning/)

 <!-- [TODO: Riktlinje för intyget? Behövs subspec rp?] -->

## Rättspsykiatrisk undersökning (RPU)

Personen vistas på en utredningsenhet vid rättsmedicinalverket under en period. Utredningen görs utifrån observationer under vistelsen och olika källor. Sådana källor kan vara handlingar i brottsmål, uppgifter från socialkontor och häkte, journaluppgifter, och kontakt med anhöriga om pesonen tillåter.

Olika yrkesgrupper gör delutredningar (medicinsk-psykiatrisk utredning, socialutredning, psykologutredning, omvårdnadsutredning) som ligger till grund för ett rättspsykiatriskt utlåtande som är utformat enligt rättsmedicinalverkets föreskrifter (HSLF-FS 2015:31) och utfärdas av en specialist i rättspsykiatri.

Undersökningen skall besvara domstolens frågeställningar som kan vara om APS förelåg vid gärningen respektive undersökningen, samt om personen till följd av APS saknat förmåga att inse gärningens innebörd eller att anpassa sitt handlande efter sådan insikt och om det därmed finns medicinska förutsättningar att överlämna honom till RPV. Man rekommenderar även huruvida den rättspsykiatriska vården bör ges med SUP. Man kan även uttala sig om huruvida det till följd av den psykiska störningen finns risk för återfall i brottslighet av allvarligt slag.

## Rättspsykiatrisk vård efter dom

Den rättspsykiatriska vården (att jämföra med rättspsykiatrisk utredning) startar efter att domen vunnit laga kraft. Det är en icke tidsbestämd påföljd. Fyra månader efter att domen vunnit laga kraft ansöker chefsöverläkaren om fortsatt vård (med SUP enligt LRV §16a, utan SUP enligt §12a). Fortsatt LRV prövas efter chefsöverläkarens ansökan i förvaltningsrätten var 6:e månad. Notera att det för fortsatt rättspsykiatrisk vård endast krävs en psykisk störning som ej behöver vara av allvarlig grad. Ett exempel är drogberoende med upprepade återfall, där APS ej uppfylls mellan återfallen.

<!-- Diagnoser se notes/rpv_huvuddiagnos.csv -->

Syftet med vården är att förbättra patientens tillstånd och samhällsskydd genom inkapacitering och att minska risken för återfall i brottslighet. 

### Vårdens innehåll

Ett vanligt förlopp är enligt följande.

**De första 1-6 månaderna**: Utredning, Missbruk, HCR-20, Patientteam, Medicinering, Gå ut med personal

**Följande 1-12 m:** Till Rehabiliteringsavd, Frigång, Permissioner, Psykologbedömning, Neuropsykiatrisk utredning

**Därefter:** Aktivering, Sysselsättning, Veckoschema, Missbruksfrihet, Brottsbearbetning, Boende (vanligen LSS, stödboende)

**Därefter, i rättspsykiatrisk öppenvård:** Behandlingshem, särskilt boende, lägenhet.

### Friförmåner

Under den rättspsykiatriska vården kan patienten ges friförmåner såsom frigång på området och permissioner utanför detsamma.

För rättspsykiatrisk vård med SUP måste chefsöverläkaren ansöka om permissioner och Frigång (LRV §10a). Utan SUP beslutar chöl om friförmåner och kan själv besluta att LRV skall upphöra (§16a ?).

Prognos grovt: 1/3 bättre inom ett år, 1/3 längre tid, 1/3 "aldrig".

## Annan rättpsykiatrisk öppenvård

Förutom de personer som dömts till RPV kan den rättspsykiatriska öppenvården även ta hand om personer från frivård eller kriminalanstalt som dömts med föreskrift om behandling av missbruk eller psykiska problem och som haft återkommande våldskriminalitet. Frivården har då föreskrivit regler och kan ge sankioner om dessa bryts. Den prioriterade målsättningen inom sådan rättspsykiatrisk öppenvård är vanligen våldsriskreduktion.

Ibland tar rättspsykiatriska vårdenheter även hand om patienter från övriga psykiatrin som har psykisk sjukdom, personlighetsstörning eller substansberoende med våldsbeteende. Detta är frivillig vård, där patienten ibland motiveras av att man annars måste avsluta kontakterna med allmänpsykiatrin och kanske gå miste om viss behandling.


## Allvarlig psykisk störning

Hit räknas väsentligen psykoser och psykosliknande tillstånd med minskad förmåga till verklighetsprövning.

Psykosliknande tillstånd med minskad förmåga till verklighetsprövning kan förekomma vid tex hjärnskada, intellektuell funktionsnedsättning, demens, konfusion, och svår autism. Själva diagnosen räcker inte, utan det krävs också en påtaglig beteendestörning till följd av tillståndet.

Vid antisocialt personlighetssyndrom, psykopati, pedofili, och sexuell sadism kan gärningarna vara mycket stötande men personen döms vanligen ej till rättspsykiatrisk vård eftersom personen har bevarad verklighetsprövning (vanligen får de ej heller något ångestpåslag vid gärningen).

Vid psykossjukdom, bipolär sjukdom, psykotisk eller suicidal depression, svår autism blir det vanligen dom till RPV snarare än fängelse.

Resonemang om vad som räknas som en APS återfinns i [regeringens proposition (1990/91:58), Psykiatrisk tvångsvård m.m., särskilt sid. 82-87](https://www.riksdagen.se/sv/dokument-lagar/dokument/proposition/om-psykiatrisk-tvangsvard-mm_GE0358/html). Dock har praxis i vissa fall förändrats. Exempelvis krävs vanligen en högre grad av suicidalitet än vad som beskrivs i propositionen för att APS skall anses föreligga.

## Riskbedömning

Vid RPU görs riskbedömning för att bedöma om LRV med med särskild utskrivningsprövning skall rekommenderas. Det görs också under LRV för att bedöma möjlighet till frigång, permission, öppenvård, och vårdavslut. Skattningsinstrument används, där standard är HCL-20 version 3.

Det saknas evidens för att behandling inom rättspsykiatrisk vård är riskreducerande avseende återfall i våldsbrott. Det saknas även studier av rättspsykiatriska insatser och andra utfall. Behandling och bedömning i rättspsykiatrisk vård har kartlagts av SBU. Slutsatsen blir att man tillsvidare får använda de kliniska riktlinjer som finns och bedriva forskning. 

<!-- Se Behandling och bedömning i rättspsykiatrisk vård SBU Kartlägger, 264/2017 -->
<!-- Läkemedelsbehandling inom rättspsykiatrisk vård, SBU Utvärderar, 286/2018 -->
<!-- Psykologiska behandlingar och psykosociala insatser i rättspsykiatrisk vård, SBU Utvärderar, 287/2018.  -->


## Juridisk terminologi

**Gripen:** Gripande är det svenska juridiska begreppet för polismans rätt att göra ett tillfälligt frihetsberövande av en person som misstänks för brott. Om det finns skäl att anhålla en person kan ett beslut om att gripa personen i brådskande fall fattas av en polis. Den som gripits ska förhöras så snart som möjligt. Efter förhöret beslutar åklagaren att den gripne ska anhållas, om det finns skäl för det. Den som är gripen får hållas kvar högst 12 timmar utan anhållan (rättegångsbalken 2 kap 9 §).

**Anhållen:** I avvaktan på att domstol ska pröva en fråga om häktning, eller om det är av stor vikt för utredningen. Beslut fattas av åklagare. På tredje dagen måste åklagaren göra häktningsframställan. 

**Häktad:** På sannolika skäl misstänkt för brott som kan ge fängelse i ett år eller mer får häktas om det finns risk för att hen kommer att hålla sig undan, försvåra utredningen eller fortsätter att begå brott, är okänd och vägrar uppge sitt namn och sin adress, eller inte är folkbokförd i Sverige och det finns risk för att personen lämnar landet. Beslut om häktning fattas av domstol. Åtal skall i normalfallet väckas senast inom 14 dagar.

**Laga kraft:** En dom vinner Laga kraft 3 veckor efter tingsrättsdom och 4 veckor efter hovrättsdom.

Den som är gripen, anhållen eller häktad sitter inlåst och har begränsad kontakt med andra personer, förutom sin advokat. Gripna och anhållna personer placeras normalt i polisarrest vid en polisstation. Häktade personer placeras i häkte, som Kriminalvården ansvarar för. 


## Resurser

### Artiklar

Andreasson H. et al. (2014). Predictors of length of stay in forensic psychiatry: The influence of perceived risk of violence. International Journal of Law and Psychiatry, 37,  635-642.  [@Andreasson2014]

Berg, J. M. et al. (2013). Misconceptions regarding psychopatic personality: implications for clinical practice and research. Neuropsychiatry 3: 63-74.  [@Berg2013]

Glenn A.L., Raine A., (2014). Neurocriminology: implications for the punishment, prediction and prevention of criminal behavior. Nature Review Neuroscience, 15, 54-63.  [@Glenn2014]

Sariaslan A., Lichtenstein, P., Larsson, H. & Fazel, S. (2016). Triggers for violent criminality in patients with psychotic disorders. JAMA Psychiatry, 73, 796-80. [@Sariaslan2016]

### Böcker

Herlofson, J. (2016). Psykiatri. (Upplaga 2:1). Lund: Studentlitteratur. (sid. 829-846). 

Grönwall, L. & Holgersson, L. (2018). Psykiatrin, tvånget och lagen. (6. uppl.) Lund: Norstedts juridik.

### Webbsidor

Kriminalvarden.se: KRIM:VÅRD En orientering om kriminalvården; organisation, behandling och vård, häkten, anstalter och frivård (uppdaterad 2018).

[Polisen.se: Gripen, anhållen eller häktad](https://polisen.se/lagar-och-regler/gripen-anhallen-eller-haktad/)

Sturup J. (2013) Riskbedömningar för våld mot andra. Teoretiska och praktiska aspekter. 

### Rapporter

&#x1F517; [SOU 2015: 52. Rapport från Bergwallkommissionen. Sid. 17-21, 615-627, 648-651.](https://www.regeringen.se/rattsliga-dokument/statens-offentliga-utredningar/2015/06/sou-2015-52/)

&#x1F517; [SOU 2012:17 (2012). Psykiatrin och lagen – tvångsvård, straffansvar och samhällsskydd. Sid. 249-300.](https://www.regeringen.se/rattsliga-dokument/statens-offentliga-utredningar/2012/04/sou-201217/)

Riskbedömningarinom psykiatrin Kan våld i samhället förutsägas? En systematisk litteraturöversikt November 2005 [@Sbu2005]


### Lagtexter

&#x1F517; [Lag (1991:1137) om rättspsykiatrisk undersökning](https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/lag-19911137-om-rattspsykiatrisk-undersokning_sfs-1991-1137)

&#x1F517; [Förordning (1991:1413) om rättspsykiatrisk undersökning](https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/forordning-19911413-om-rattspsykiatrisk_sfs-1991-1413)

&#x1F517; [Lag (1991:2041) om särskild personutredning i brottmål, m.m.](https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/lag-19912041-om-sarskild-personutredning-i_sfs-1991-2041)

&#x1F517; [HSLF-FS 2015:31 Rättspsykiatrisk undersökning](https://lagen.nu/hslf-fs/2015:31)

&#x1F517; [SOSFS 2009:12 Rättsmedicinalverkets föreskrifter om läkarintyg enligt 7 § lagen (1991:2041) om särskild personutredning i brottmål, m.m.](https://www.socialstyrelsen.se/regler-och-riktlinjer/foreskrifter-och-allmanna-rad/konsoliderade-foreskrifter/200912-om-lakarintyg-enligt-7--lagen-19912041-om-sarskild-personutredning-i-brottmal-m.m/)

&#x1F517; [Lag (1991:1129) om rättspsykiatrisk vård](https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/lag-19911129-om-rattspsykiatrisk-vard_sfs-1991-1129)

&#x1F517; [Lag (1991:1128) om psykiatrisk tvångsvård](https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/lag-19911128-om-psykiatrisk-tvangsvard_sfs-1991-1128)

&#x1F517; [Kungörelse (1974:152) om beslutad ny regeringsform](https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/kungorelse-1974152-om-beslutad-ny-regeringsform_sfs-1974-15)

&#x1F517; [Fängelseförbudet: Brottsbalken 30 kap 6§](https://lagen.nu/1962:700#K30)

&#x1F517; [Om överlämnande till särskild vård: Brottsbalken och 31 kap 3§](https://lagen.nu/1962:700#K31)

### Se även

Psykiatrisk tvångsvård  och rättspsykiatrisk vårdHandbok med information och vägledning  för tillämpningen av Socialstyrelsens föreskrifter och allmänna råd om psykiatrisk tvångsvård och rättspsykiatrisk vård (SOSFS 2008:18
https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/artikelkatalog/ovrigt/2009-126-114_2009_126_114.pdf


Psykiatrin och lagen – tvångsvård, straffansvar och samhällsskydd, Betänkande av Psykiatrilagsutredningen, 2012, https://www.regeringen.se/49b69f/contentassets/5b38a9eb3f8f468680e71ae6c2707cd4/psykiatrin-och-lagen---tvangsvard-straffansvar-och-samhallsskydd-sou-201217-del-1

Säkerhetvid psykiatrisk tvångsvård, rättspsykiatrisk vård och rättspsykiatrisk undersökningsverksamhet, Handbok med information och vägledning för tillämpningen av Socialstyrelsens föreskrifter om säkerhet vid sjukvårdsinrättningar som ger psykiatrisk tvångsvård och rättspsykiatrisk vård samt vid enheter för rättspsykiatrisk undersökningsverksamhet (SOSFS 2006:9), Socialstyrelsen, https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/artikelkatalog/handbocker/2007-101-4_rev.pdf

JURIS Online, betaltjänst, http://www.juris.se/web/page.aspx?refid=10

Lawline, gratis tjänst, https://lawline.se/

Regeringens proposition 1990/91:58 om psykiatrisk tvångsvård mm (resonemang om allvarlig psykisk störning främst s82-102) https://www.riksdagen.se/sv/dokument-lagar/dokument/proposition/om-psykiatrisk-tvangsvard-mm_GE0358




