# Juridik

## Psykiatrisk tvångsvård

Insikt god, dålig, partiell, växlande viktigt vid LPT!


## Sekretess

Om den som utsatts för brott är vuxen ska det vara fråga om ett begånget brott där lägsta straff är fängelse i ett år (till exempel grov misshandel, olaga frihetsberövande, mord, dråp, våldtäkt, mordbrand, rån). Man kan också lämna uppgifter om försök till brott där det inte är stadgat lindrigare straff än fängelse i två år (till exempel mord, dråp, människorov, våldtäkt).

Offentlighets- och sekretesslag (2009:400) 10 kap 23 §  Om inte annat följer av 19–22 §§ får en uppgift som angår misstanke om ett begånget brott och som är sekretessbelagd enligt 24 kap.2 a eller 8 §, 25 kap. 1 §, 2 § andra stycket eller 3–8 §§, 26 kap.1–6 §§, 29 kap. 1 §, 31 kap. 1 § första stycket, 2 eller 12 §, 33 kap. 2 §, 36 kap. 3 § eller 40 kap.2 eller 5 § lämnas till en åklagarmyndighet, Polismyndigheten, Säkerhetspolisen eller någon annan myndighet som har till uppgift att ingripa mot brottet endast om misstanken angår

- brott för vilket det inte är föreskrivet lindrigare straff än fängelse i ett år,
- försök till brott för vilket det inte är föreskrivet lindrigare straff än fängelse i två år, eller
- försök till brott för vilket det inte är föreskrivet lindrigare straff än fängelse i ett år, om gärningen innefattat försök till överföring av sådan allmänfarlig sjukdom som avses i 1 kap. 3 § smittskyddslagen (2004:168). Lag (2014:633).

Lawline

Verksamhetchefen: Om en person skall ämna sjukhuset där det finns fara för att den skall skada ngn skall personen och polismyndigheten kontaktas.

Mord, våltäkt, grov misshandel = minst 1 år

Skyldighet för verksamhetschef, eller den som fått detta delegerat, att om en patient som lämnar  eller  avser  lämna  sjukhuset  är farlig  för  någon  annans  personliga  säkerhet  eller  sitt eget liv omedelbart underrättar någon närstående till patienten och att, om patienten är farlig  för  viss  person,  även  denna  samt,  om  det  behövs,  lämplig  myndighet,  ofta  polisen  (2 § 4 p förordningen om verksamhetschef). Se äv. under rubrik Trafiknykterhetsbrott.
