# Kognitiv betendeterapi {#cbt}

I detta kapitel beskrivs översiktligt principer för utförandet av kognitiv betendeterapi (KBT), inklusive metoder som kan användas samt tips för tillämpning vid specifika problem såsom ångestsjukdomar, depression och självskada. [Alt beskriv behandlingsprinciper för KBT integrerat i kapitlen om sjukdomar?]

Teroretisk ram beskrivs i kapitel \@ref(behavioural-psychology), där en översikt ges för associativ och operant inlärning, samt hur beteenden kan kartläggas och analyseras.

## Behandlingsprinciper

Framgångsrik behandling kan endast ske när det som övas under terapisessionerna kan tillämpas i verkligheten, vilket förutsätter generalisering. Målsättningen vid behandling är därför att förstärka alternativa beteenden som gör att patienten kommer i kontakt med naturliga förstärkare i livet, vilket ger drivkraft till förändring. För att uppnå detta kan beteenden aktualiseras i relation till terapeuten, och det nya beteendet övas i samtalsrummet.

Tips: Behandlaren kan använda beteendeanalys på själva terapin, dvs analysera de beteenden patienten och terapeuten har och hur de påverkar behandlingen. Man kan då diskriminera de beteenden som fungerar för patienten och undvika exempelvis bestraffande beteenden (påstridighet kan tex vara ett sådant).

**Tabell:** Praktiska tips till behandlaren

- Skapa förutsättning som ökar sannolikheten för aktivering av naturliga/befintliga förstärkare i patientens liv.
- Bredda beteendereportoaren med adekvata färdigheter.
- Träna förmågan till diskriminering.
- Öka språklig kontroll av stimuli och konsekvenser.
- Ändra relationsrespons, "att tänka om".
- Identifiera och påverka etablerande omständigheter.
- Mål och problem bör furmuleras tydligt i ord.
- Uppmuntra själviakttagelse, efterfråga vad patienten kan iaktta. Kan innebära att patienten upptäcker nya möjligheter, upplever förändringar i affekt.

## Problemlösning

Problemlösning är en viktig färdighet och behandlaren kan bidra genom att visa på goda strategier för problemlösning. Poängen är inte att bara lösa ett konkret problem, utan att öva upp sin problemlösningsfärdighet. Behandlaren kan betona att det är egna beteenden och konsekvenser av dessa som man bör ta ansvar för, inte andras beteende. Försök att kontrollera andras beteende är ett stimulus för motkontroll från den andre, dvs beteenden som motsätter sig kontrollförsöket, vilket kan leda till en spiral. Personen bör uppmuntras att själv se och beskriva vilka möjligheter hen har för att ändra sitt beteende, exempelvis genom att göra en lista. Även dåliga alternativ kan då listas (tex att säga upp sig). Problemlösningsfärdighet innebär bland annat att kunna skapa olika alternativ och inte låsa sig vid ett.

## Beteendekontrakt 

Ref (ABC s 205, Maglieri 2003):

1. Tydlig överenskommelse om mål.
2. Försäkrar sig om att alla inblandade har tillgång till att följa processen mot dessa mål och utvärdera framgång.
3. Beskriver vad som krävs av dem som kontraktet omfattar.
4. Tydligt att alla inblandade varit aktiva i hur det är formulerat.

## Kliniskt problem: Självskada på avdelningen

Självskada kan upprätthållas av både negativ förstärkning (minskning av desperation) och positiv förstärkning (tröstande respons från andra). Grundprincipen vid behandling är att identifiera förstärkare av beteendet, tex dramatiska åtgärder efter självskada, och minska dessa. Självskada bör följas av neutralt bemötande där man avstår drastiska åtgärder och likaså avstår omprövningar av behandlingen i anslutning till självskada. Att dra tillbaks alla förstärkare (tex uppmärksamhet) är svårt och riskerar orsaka kompensatorisk ökning av beteendet. Istället medvetandegörs att patienten har legitima anspråk på basala förstärkare, tex omtanke, inflytande och ges uppmärksamhet jämnt fördelat över tid, dvs inte som respons på skadliga beteenden. På övergripande nivå arrangeras en miljö som inte förstärker destruktiva beteenden [exempel?]. Man bör även benämna (för både patient och personal) att det handlar om att ta ansvar för sitt eget beteende och dess konsekvenser på omgivningen, snarare än att ta över ansvar för andras beteende.

En metod som kan användas är diferentiell förstärkning av vissa beteenden. Då definieras ett antal beteenden som kommer att förstärkas selektivt. Man kan göra en överenskommelse med patienten om beteenden som kommer att efterföljas av något som patienten eftersträvar (ex permission), då formulerat positivt. 

Se även social färdighetsträning i avsnitt \@ref(social-skills).

## Social färdighetsträning {#social-skills}

Modellinlärning den mest effektiva metoden (ABC s 195, Rosenberg 1989). Gruppverksamhet att rekommendera. Gruppen erbjuder modeller som är lättare att identifiera sig med än vårdpersonal.

Hjälper patienten att utveckla basala färdigheter:
- Att tala om för omgivningen att man behöver hjälp
- Att säga sin mening klart och tydligt
- Att med ord uttrycka önskemål och invänta svar

## Exponering

Exponering är en behandlingsmetod vid ångesttillstånd (ref Barlow 2002). Den utgår från att beteenden som styr av konsekvenser, exempelvis undvikande, spelar en central roll. Effekterna av exponering kan beskrivas både med respondent inlärning (utsläckning) och operant inlärning (bryta undvikande). Metoden innebär att patienten successivt närmar sig det som väcker negativa känslor och stannar kvar i situationen, vilket leder till _utsläckning_ av beteendet. I frånvaro av undvikande kan ominlärning ske (ref Craske 2008). Exponeringsprocessen bör vanligen vara gradvis, utdragen och upprepad. Genom att få tillgång till nya konsekvenser av ett beteende ökar beteendereportoaren [= Responsutvidgning?], vilket i sin tur kan öppna situationer som är naturliga förstärkare av önskade beteenden. 

Även relationsinramning har betydselse. Känslor och inre beteenden (tex hjärtklappning) som uppträder i den situation (tex samtal) som är besvärlig för patienten kan leda till formulering av tankar såsom "nu märker alla att jag mår dåligt", vilka genom exponering kan leda till omformulering, tex "nu har jag hjärtklappning och då kommer tanken ...".

[TODO : Beskriv relationsinramning?]

Patienten kan uppmanas att observera sig själv och att analysera vilken funktion de inre responserna har. Man kan då sträva efter att diskriminera tankar som tankar snarare än verklighet. Här kan det hjälpa att ge psykoedukation om exempelvis vad som händer i kroppen när man blir rädd (ifall problemet är ångest). Genom att uppmuntra patienten att iaktta sitt beteende och dess konsekvenser kan hen upptäcka nya möjligheter för alternativa beteenden, uppleva förändring i affekt och klara av att göra saker som fungerar bättre.

Ett annat knep är att och ifrågasätta verbala konstruktioner som personen skapat genom att jämföra hur de går ihop med andra verbala konstruktioner [TODO : Förtydliga detta stycke].

En utgångspunkt för behandling kan vara att identifiera och fokusera på en gemensam faktor som ofta finns i olika situationer, tex inre fenomen (känslor, kroppsliga symtom såsom hjärtklappning). _Introceptiv exponering_ innebär att patienten utsätts för kroppsliga symtom (tex yrsel, overklighetskänslor) eller tankar som väcker obehag.

Förutsättningar för exponeringsbehandling:

- Tid att stanna i situationen tills rädslan avtar naturligt och inte som resultat av flykt.
- Upprepa förloppet inom kort tid, dvs flera gånger i veckan.
- För att uppnå generalisering bör exponering sker i olika situationer.

## Beteendeaktivering

Beteendeaktivering vid depression motsvarar exponering vid ångesttillstånd (Martell 2001). Ökad aktivering öppnar möjligheter för nya konsekvenser som ifall de är belönande kan hjälpa till att bryta det passiva beteendet. :eget:
