# Psykiatrisk tvångsvård

Se även kapitel \@ref(rattspsykiatri) om rättspsykiatrisk vård.

## Allvarlig psykisk störning

Se Regeringens proposition 1990/91:58 om psykiatrisk tvångsvård mm (resonemang om allvarlig främst s82-102) https://www.riksdagen.se/sv/dokument-lagar/dokument/proposition/om-psykiatrisk-tvangsvard-mm_GE0358

Vid exempelvis autism bedöms autismens grad i fråga om tvångsmässighet, rigiditet, mentaliseringsförmåga, och komorbiditet med ID. APS kan tex föreligga om tillståndet är psykosliknande.

Det har ingen betydelse för bedömningen av APS om tillståndet är självförvållat.

Följer personens agerande en rational, även om det är överdrivet? Om handlandet är ändamålsenligt, instrumentellt, kan man tendera att inte se det som en APS.

Genombrott av impulsivitet, raptus, vrede, "det blev elt svart", "jag blev någon annan", räknas ej som APS.

## Vem får göra vad?

Kvarhållning före bedömning, JA, kan göras av läkare i allmän tjänst.
Transport: Lokalt bestämt alltid 2 personal med för pat på LPT, exv mellan avdelningar.
LPT-permission ok, motivera, se på pats sjukhistoria, anhöriga.
Paragraf 47 primärjouren diskuterar m bakjouren om ej leg läk.

Tvångsåtgärd före intagningsbeslut

## Äldrejuridik

BPSD och LPT-lagen och etiken [Från kurs i Äldrepsykiatri]

Låst dörr - olagligt men i praktiken kodlås etc

Grenbälte, sittbord - endast frivilligt

Binda i sängen (tex höftfraktur) nej men sänggrindar kan ordineras, dock som bältning i LPT

Lura i läkemedel - ej tillåtet

LPT gäller även demens om det är en samtidig allvarlig psykisk störning (tex konfusion, depression m su risk, psykos)

Nödvändig somatisk behandling kan ges vid livshotande akuta tillstånd

Giftermål: Man måste förstå vad man gör (vigselförrättaren kontrollerar)

Testamente: Man skall veta vad man gör

Fullmakt: Skall ej skrivas om man ej vet vad man gör

Gäller avtal om man ej vet vad man gör: Nej, läkare kan skriva intyg

Anmälningsplikt körkort

Vapen hos avliden - kontakta polisen

Frågor och svar om äldrejuridik:

https://docplayer.se/9470618-Fragor-och-svar-om-aldrejuridik-version-2015-03-10-sid-1-6-karin-sparring-bjorksten-med-dr-overlakare-karin-sparring-bjorksten-sll.html


## LPT lagtext med sammanfattningar och kommentarer

### Inledande bestämmelser

Här defineras i vilka situationer lagen tillämpas. Tvångsåtgärd skall stå i proportion med syftet med tvångsåtgärden. Den skall göras skonsamt och med största möjliga hänsyn till patienten, och endast om patienten inte kan förmås att frivilligt medverka.

>1 § Föreskrifterna i hälso- och sjukvårdslagen (2017:30) och patientlagen (2014:821) gäller all psykiatrisk vård.  Kompletterande föreskrifter om psykiatrisk vård som är förenad med frihetsberövande och annat tvång (tvångsvård) ges i denna lag.

>Föreskrifter om psykiatrisk tvångsvård finns också i lagen (1991:1129) om rättspsykiatrisk vård.

>Det som sägs i denna lag om en region gäller även en kommun som inte ingår i en region.

>Med chefsöverläkare avses i denna lag chefsöverläkaren vid den sjukvårdsinrättning där patienten är inskriven.  Lag (2019:876).

>2 § Tvångsvård enligt denna lag ges som sluten psykiatrisk tvångsvård eller, efter sådan vård, som öppen psykiatrisk tvångsvård. Vård som ges när patienten är intagen på en sjukvårdsinrättning benämns sluten psykiatrisk tvångsvård.  Annan vård enligt denna lag benämns öppen psykiatrisk tvångsvård.

>Tvångsvården ska syfta till att sätta patienten i stånd att frivilligt medverka till nödvändig vård och ta emot det stöd som han eller hon behöver. Lag (2008:415).

>2 a § Tvångsåtgärder vid vård enligt denna lag får användas endast om de står i rimlig proportion till syftet med åtgärden.  Är mindre ingripande åtgärder tillräckliga, skall de användas.

>Tvång skall utövas så skonsamt som möjligt och med största möjliga hänsyn till patienten. Lag (2000:353).

>2 b § Tvångsåtgärder i syfte att genomföra vården får användas endast om patienten inte genom en individuellt anpassad information kan förmås att frivilligt medverka till vård. De får inte användas i större omfattning än vad som är nödvändigt för att förmå patienten till detta. Lag (2000:353).

### Förutsättningar för tvångsvård

Här beskrivs de individuella förutsättningarna för att en person skall tvångsvårdas:

- Allvarlig psykisk störning (APS) tillsammans med personliga förhållanden i övrigt (övrigt stöd, möjlighet till frivillig behandling osv)
- Oundgängligt behov av psykiatrisk slutenvård. Här skall farlighet mot personen själv eller andra vägas in.
- Motsätter sig vård eller att man har goda skäl att anta att vården inte kan ges med  samtycke

>3 § Tvångsvård får ges endast om patienten lider av en allvarlig psykisk störning och på grund av sitt psykiska tillstånd och sina personliga förhållanden i övrigt

>1. har ett oundgängligt behov av psykiatrisk vård, som inte kan tillgodoses på annat sätt än genom att patienten är intagen på en sjukvårdsinrättning för kvalificerad psykiatrisk dygnetruntvård (sluten psykiatrisk tvångsvård), eller

>2. behöver iaktta särskilda villkor för att kunna ges nödvändig psykiatrisk vård (öppen psykiatrisk tvångsvård).

>En förutsättning för vård enligt denna lag är att patienten motsätter sig sådan vård som sägs i första stycket, eller det till följd av patientens psykiska tillstånd finns grundad anledning att anta att vården inte kan ges med hans eller hennes samtycke.

>Tvångsvård får inte ges om patientens psykiska störning enligt första stycket utgör enbart en utvecklingsstörning.

>Vid bedömning av vårdbehovet enligt första stycket ska det även beaktas, om patienten till följd av sin psykiska störning är farlig för annans personliga säkerhet eller fysiska eller psykiska hälsa. Lag (2008:415).

### Intagning för tvångsvård

Ett **intagningsbeslut** kräver att det finns ett vårdintyg. Vårdintyget skall grundas på en läkarundersökning. Om en person inte medverkar till sådan underökning kan denne omhändertas <!-- [TODO: Hur sker omhändertagandet] -->.

Frågan om intagning ska avgöras skyndsamt av en chefsöverläkare inom psykiatrin (ej den läkare som skrivit vårdintyget) och senast 24 timmar efter patientens ankomst till vårdinrättningen. För vårdintyg som utfärdats i primärvården måste intagningsbeslut ske inom fyra dagar (och inom 24 tim från ankomst).

#### Tiden mellan vårdintyg med kvarhållning och intagningsbeslut 

Efter att ett vårdintyg utfärdats får personen hållas kvar (**kvarhållning** enligt 6 §) på vårdinrättningen fram tills det att en bedömning avseende intagning gjorts. Under detta tidsintervall får tvångsåtgärder tillämpas (efter kvarhållningsbeslut) för att:

- Hindra patienten att lämna vårdinrättningen (6 §)
- Upprätthålla ordningen (6 §)
- Tillgodose säkerheten i vården (6 §)
- Kortvarigt spännas fast med bälte (6 a §)\*
- Kortvarigt hållas avskild (6 a §)\*
- Vid överhängande fara för patientens liv eller hälsa får nödvändig behandling ges (6 a §)

\* För patienter <18 år måste det vara uppenbart att andra åtgärder inte är tillräckliga; för fastspänning (högst en timme) även att det finns omedelbar fara för att patientens annars lider allvarlig skada; för avskiljning (högst två timmar) att hen genom aggressivt beteende allvarligt försvårar vården av de andra patienterna.

Ovanstående beslut enligt om tvångsåtgärder 6 § får göras av läkare och beslut enligt 6 a § får fattas av legitimerad läkare.

Patienten kan även **kroppsvisiteras** eller ytligt kroppsbesiktigas (efter besklut av Chefsöverläkaren), för kontroll av att denne inte bär på sig narkotika, alkohol, dopningsmedel, injektionssprutor eller kanyler, egendom som kan skada honom eller henne själv eller någon annan (och liknande, se 21 §). Skriftliga meddelanden får inte granskas. Om möjligt skall ett vittne närvara när åtgärden utförs.

>4 § Ett beslut om intagning på en sjukvårdsinrättning för tvångsvård får inte fattas utan att ett läkarintyg (vårdintyg) har utfärdats, av vilket det framgår att det finns sannolika skäl för att förutsättningarna för sluten psykiatrisk tvångsvård av patienten är uppfyllda. Vårdintyget ska grundas på en särskild läkarundersökning.

>En undersökning för vårdintyg får företas endast om det finns skälig anledning till det. Undersökningen utförs av en legitimerad läkare. Om undersökningen inte kan utföras med patientens samtycke, får patienten tas om hand för undersökning. Beslut om sådant omhändertagande får fattas endast av en läkare i allmän tjänst eller av en läkare som enligt avtal med regionen har till uppgift att utföra undersökningar för vårdintyg. Lag (2019:876).

>5 § Vårdintyget får utfärdas endast i omedelbar anslutning till undersökningen. Det ska, utöver ett uttalande enligt 4 § om förutsättningarna för tvångsvård av patienten, innehålla en redogörelse för den psykiska störningen och de omständigheter i övrigt som ger upphov till vårdbehovet.

>Vid utfärdande av vårdintyg tillämpas bestämmelserna om jäv i 16–18 §§ förvaltningslagen (2017:900) även i fråga om läkare som utövar yrket enskilt.

>Den läkare som har utfärdat vårdintyget ska se till att det snarast kommer till den sjukvårdsinrättning där frågan om intagning för tvångsvård ska prövas. Lag (2018:798).

>6 § En patient får, sedan vårdintyg har utfärdats, efter beslut av läkare hållas kvar på vårdinrättningen tills frågan om intagning har avgjorts. Om andra åtgärder inte är tillräckliga, får det tvång användas som är nödvändigt för att hindra patienten att lämna den del av vårdinrättningen där patienten skall vistas, för att upprätthålla ordningen på inrättningen eller för att tillgodose säkerheten i vården.

>Om det är nödvändigt får patienten, sedan beslut om att hålla kvar denne har fattats, kroppsvisiteras eller ytligt kroppsbesiktigas för kontroll av att denne inte bär på sig egendom som anges i 21 §. Föreskrifterna i 23 och 24 §§ skall därvid tillämpas. Lag (2000:353).

>6 a § I sådana fall som anges i 19 eller 20 § får en patient som hålls kvar enligt 6 § kortvarigt spännas fast med bälte eller liknande anordning eller kortvarigt hållas avskild från de andra patienterna. Om patienten är under 18 år får dock, i sådana fall som avses i 19 a eller 20 a §, patienten spännas fast med bälte högst en timme och hållas avskild högst två timmar.

>En patient som hålls kvar enligt 6 § får, om det finns en överhängande fara för patientens liv eller hälsa, ges nödvändig behandling.

>Beslut enligt denna paragraf fattas av legitimerad läkare.  Chefsöverläkaren får besluta om förlängning av de tider som avses i första stycket under de förutsättningar som anges i 19-20 a §§. Lag (2020:354).

>6 b § Frågan om intagning för sluten psykiatrisk tvångsvård ska avgöras skyndsamt efter undersökning av patienten, senast 24 timmar efter dennes ankomst till vårdinrättningen. Ett beslut om intagning får inte grundas på ett vårdintyg som är äldre än fyra dagar.

>Beslut om intagning fattas av en chefsöverläkare vid en enhet för psykiatrisk vård. Beslutet får inte fattas av den läkare som har utfärdat vårdintyget. Lag (2008:415).

### Intagningsbeslut

<!-- [TODO: Mer om detta] -->

Intagningsbeslut fattas på de grunder som redogörs ovan.

Om en patient redan vistas på en sjukvårdsinrättning för frivillig psykiatrisk vård, får chefsöverläkaren vid den enhet där patienten vårdas besluta om sluten psykiatrisk tvångsvård (enligt 11 §) när förutsättningarna för psykiatrisk tvångsvård är uppfyllda enligt ovan, och patienten dessutom till följd av sin psykiska störning kan befaras komma att allvarligt skada sig själv eller någon annan. Då gäller:

- Ett vårdintyg av annan läkare måste finnas. 
- Intagningsbeslutet skall fattas inom 24 tim efter vårdintyget
- Mellan vårdintyg och intagningsbeslut gäller möjligheter till tvångsåtgärder enligt 6 och 6 a §§ [TODO: Räcker kvarhållning?]
- Beslutet skall av chefsöverläkaren senast dagen efter beslutet underställas förvaltningsrättens prövning
- Om rätten bifaller en sådan ansökan får tvångsvården pågå under (högst) fyra månader, med möjlighet till förlängning enligt 9 §


### Tvångsvård efter beslut av rätten

Här behandlas förlängning av tvångsvård utöver fyra veckor eller om tvångsvården skall växla mellan öppen och sluten tvångsvård, samt ytterligare förlängning av dessa tider. Chefsöverläkaren ansöker då hos förvaltningsrätten om medgivande för sådan vård.

Om rätten bifaller ansökan, får vården pågå under högst fyra månader, räknat från dagen för beslutet om intagning. Efter ny ansökan av chefsöverläkaren (skall ha inkommit till rätten innan tiden för gällande beslut löpt ut) får rätten medge att tvångsvården fortsätter längre, högst sex månader åt gången, räknat från den dag då förvaltningsrätten meddelar beslut i frågan. Till ansökan om fortsatt öppen psykiatrisk tvångsvård ska det fogas en uppföljning av den samordnade vårdplanen (se nedan). Har en ansökan kommit in till förvaltningsrätten, får tvångsvården fortsätta i avvaktan på förvaltningsrättens beslut. Om vården fortsätter ska den ges i den form som föreskrivs i det senaste beslutet om tvångsvård. Avslår rätten ansökan, ska vården upphöra omedelbart.

I ansökan anges:

- Om det gäller sluten eller öppen tvångsvård
- Grund för tvångsvården
- Överväganden som har gjorts avseende vård i annan form
- Redogörelse för stöd och den behandling som planeras under och efter vistelsen på vårdenheten (bifogas)

För öppen psykiatrisk tvångsvård även:

- Vilka särskilda villkor som rätten bör föreskriva
- Patientens inställning till dessa villkor 
- Samordnad vårdplan (bifogas)

**Samordnad vårdplan** ska innehålla uppgifter om

- det bedömda behovet av insatser från sjukvården och kommunen
- eventuella åtgärder som vidtas av andra än regionen eller kommunen
- vilken enhet vid regionen eller kommunen som ansvarar för respektive insats
- beslut om insatser 
- patientens inställning till insatserna i vårdplanen

Vårdplanen ska så långt möjligt utformas i samråd med patienten och, om det inte är olämpligt, med dennes närstående. Vårdplanen ska utformas i samarbete mellan de enheter vid kommunen eller regionen som svarar för insatserna.  Vårdplanen är upprättad när den har justerats av enheterna. Chefsöverläkaren ska underrätta berörd enhet vid region, kommun eller annan huvudman om beslut om öppen psykiatrisk tvångsvård.

>7 § Om chefsöverläkaren finner att patienten bör ges tvångsvård utöver fyra veckor från dagen för beslutet om intagning, ska chefsöverläkaren före utgången av fyraveckorstiden ansöka hos förvaltningsrätten om medgivande till sådan vård. Chefsöverläkaren ska även ansöka hos förvaltningsrätten om medgivande till fortsatt vård när han eller hon anser att den psykiatriska tvångsvården bör övergå i öppen eller sluten form.

>I ansökan ska det anges om vården avser sluten eller öppen psykiatrisk tvångsvård.

>I ansökan om sluten psykiatrisk tvångsvård ska det anges vilka omständigheter som utgör grund för tvångsvården och vilka överväganden som har gjorts i fråga om vård i annan form för patienten. Till ansökan ska det fogas en redogörelse för det stöd och den behandling som planeras för patienten under och efter vistelsen på vårdenheten.

>I ansökan om öppen psykiatrisk tvångsvård ska det anges vilka omständigheter som utgör grund för tvångsvården, vilka särskilda villkor som rätten bör föreskriva och, så långt möjligt, patientens inställning till dessa villkor. Till ansökan ska det fogas en sådan samordnad vårdplan som avses i 7 a §. Lag (2017:369).

>7 a § En samordnad vårdplan ska innehålla uppgifter om

>- det bedömda behovet av insatser från regionens hälso- och sjukvård och kommunens socialtjänst eller hälso- och sjukvård,

>- beslut om insatser och, så långt möjligt, patientens inställning till insatserna i vårdplanen,

>- vilken enhet vid regionen eller kommunen som ansvarar för respektive insats, och

>- eventuella åtgärder som vidtas av andra än regionen eller kommunen.

>Vårdplanen ska upprättas av chefsöverläkaren, om han eller hon bedömer att patienten kommer att vara i behov av insatser enligt första stycket i samband med öppen psykiatrisk tvångsvård. Vårdplanen ska så långt möjligt utformas i samråd med patienten och, om det inte är olämpligt, med dennes närstående. Vårdplanen ska utformas i samarbete mellan de enheter vid kommunen eller regionen som svarar för insatserna.  Vårdplanen är upprättad när den har justerats av enheterna.

>Chefsöverläkaren ska underrätta berörd enhet vid region, kommun eller annan huvudman om beslut om öppen psykiatrisk tvångsvård. Lag (2019:876).

>8 § Rätten ska på ansökan enligt 7 § besluta i frågan om fortsatt vård i form av sluten eller öppen psykiatrisk tvångsvård.

>Om rätten bifaller ansökan, får vården pågå under högst fyra månader, räknat från dagen för beslutet om intagning. Lag (2008:415).

>9 § På ansökan av chefsöverläkaren får rätten medge att tvångsvården fortsätter i form av öppen eller sluten psykiatrisk tvångsvård utöver den längsta tiden enligt 8 §.  Medgivande får lämnas för högst sex månader åt gången, räknat från den dag då förvaltningsrätten meddelar beslut i frågan.

>En ansökan enligt första stycket ska ha kommit in till förvaltningsrätten innan tiden för gällande beslut om tvångsvård har löpt ut. Föreskrifterna i 7 § andra-fjärde styckena och 7 a § tillämpas på en ansökan enligt denna paragraf.

>Till ansökan om fortsatt öppen psykiatrisk tvångsvård ska det fogas en uppföljning av den samordnade vårdplanen.  Lag (2009:809).

>10 § Har en ansökan enligt 7 eller 9 § kommit in till förvaltningsrätten, får tvångsvården fortsätta i avvaktan på förvaltningsrättens beslut. Om vården fortsätter ska den ges i den form som föreskrivs i det senaste beslutet om tvångsvård.  Avslår rätten ansökan, ska vården upphöra omedelbart.  Lag (2009:809).

>11 § Om en patient är intagen på en sjukvårdsinrättning för frivillig psykiatrisk vård, får chefsöverläkaren vid den enhet där patienten vårdas besluta om sluten psykiatrisk tvångsvård när

>1. de förutsättningar som anges i 3 § första stycket 1 och andra stycket är uppfyllda, och

>2. patienten till följd av sin psykiska störning kan befaras komma att allvarligt skada sig själv eller någon annan.

>Ett sådant beslut får inte fattas utan att ett vårdintyg har utfärdats av en annan läkare än chefsöverläkaren. I fråga om vårdintyg gäller bestämmelserna i 4 § och 5 § första och andra styckena. Beslut om vård enligt första stycket ska fattas senast 24 timmar efter det att vårdintyg har utfärdats. Det som sägs i 6 och 6 a §§ gäller också vid övergång från frivillig vård till tvångsvård enligt första stycket. Lag (2008:415).

>12 § När beslut har fattats om sluten psykiatrisk tvångsvård enligt 11 §, ska beslutet av chefsöverläkaren senast dagen efter beslutet underställas förvaltningsrättens prövning.

>Anser chefsöverläkaren att tvångsvården bör fortsätta ska han eller hon senast inom fyra dagar från dagen för beslutet om sluten psykiatrisk tvångsvård ansöka hos förvaltningsrätten om medgivande till fortsatt vård. Det som sägs i 7 § andra-fjärde styckena och 7 a § ska därvid tillämpas. Lag (2000:809).

>13 § Om rätten bifaller en ansökan enligt 12 § andra stycket, får tvångsvården pågå under högst fyra månader, räknat från dagen för chefsöverläkarens beslut. I fråga om tvångsvård utöver denna tid tillämpas samma bestämmelser som vid fortsatt tvångsvård enligt 9 §. Lag (2008:415).

>Övergång från rättspsykiatrisk vård till tvångsvård enligt denna lag

>14 § När rättspsykiatrisk vård ska upphöra i fall som avses i 15 § lagen (1991:1129) om rättspsykiatrisk vård får chefsöverläkaren besluta om sluten psykiatrisk tvångsvård enligt denna lag trots att vårdintyg inte har utfärdats, om de förutsättningar som anges i 3 § första stycket 1 och andra stycket är uppfyllda.

>Föreskrifterna i 6 b § gäller inte i de fall som avses i första stycket. I stället tillämpas föreskrifterna i 12 § andra stycket och 13 §, varvid ett beslut enligt denna paragraf jämställs med beslut enligt 11 §. Lag (2008:415).

<!-- HERE -->

### Gemensamma bestämmelser om vården

>15 § Vård enligt denna lag ges på en sjukvårdsinrättning som drivs av en region. Om det finns synnerliga skäl, får regeringen bestämma att vård får ges även på någon annan vårdinrättning. På en sådan inrättning ska tillämpas det som i denna lag sägs om sjukvårdsinrättning som drivs av en region.  Lag (2019:876).

>15 a § Vård enligt denna lag skall bedrivas så att den uppfyller kraven på god säkerhet i verksamheten. Vid sjukvårdsinrättningen skall det finnas den personal, de lokaler och den utrustning som behövs för att en god säkerhet skall kunna tillgodoses i verksamheten. Det skall också finnas någon som har ansvaret för att sjukvårdsinrättningen säkerhetsanpassas och säkerhetsklassificeras samt för att säkerheten systematiskt och fortlöpande utvecklas och upprätthålls (säkerhetsansvarig). Lag (2006:247).

>16 § En vårdplan skall upprättas snarast efter det att patienten har tagits in för tvångsvård. Vårdplanen skall ange de behandlingsåtgärder och andra insatser som behövs för att syftet med tvångsvården skall uppnås och för att resultaten av dessa insatser skall kunna bestå. Så långt möjligt skall planen upprättas i samråd med patienten. Om det inte är olämpligt skall samråd ske också med dennes närstående.

>Chefsöverläkaren skall undersöka om patienten har behov av stöd från socialtjänsten. Så långt det är möjligt skall detta ske i samråd med patienten. Lag (2000:353).

>17 § I fråga om behandlingen under vårdtiden ska samråd äga rum med patienten när det kan ske. Samråd ska ske också med patientens närstående, om det inte är olämpligt.

>Behandlingsåtgärderna ska anpassas till vad som krävs för att uppnå syftet med tvångsvården enligt 2 § andra stycket.

>Om det är nödvändigt får patienten, efter chefsöverläkarens beslut, ges behandling utan samtycke. Lag (2017:369).

>Sluten psykiatrisk tvångsvård

>18 § En patient får hindras att lämna vårdinrättningens område eller den del av inrättningen där han skall vistas.

>Om andra åtgärder inte är tillräckliga, får det tvång användas som är nödvändigt för att hindra patienten att lämna vårdinrättningens område eller den del av inrättningen där denne skall vistas, för att upprätthålla ordningen på vårdinrättningen eller för att tillgodose säkerheten i vården.  Lag (2000:353).

>18 a § Chefsöverläkaren ska, så snart patientens tillstånd tillåter det, se till att patienten erbjuds ett uppföljningssamtal efter genomförd tvångsåtgärd.  Lag (2017:369).

>19 § Om det finns en omedelbar fara för att en patient allvarligt skadar sig själv eller någon annan, får patienten kortvarigt spännas fast med bälte eller liknande anordning.  Hälso- och sjukvårdspersonal ska vara närvarande under den tid patienten hålls fastspänd.

>Om det finns synnerliga skäl, får det beslutas att patienten ska hållas fastspänd längre än som anges i första stycket.

>Chefsöverläkaren beslutar om fastspänning. Inspektionen för vård och omsorg ska utan dröjsmål underrättas om beslut enligt andra stycket. Lag (2020:354).

>19 a § Om det finns en omedelbar fara för att en patient som är under 18 år lider allvarlig skada och det är uppenbart att andra åtgärder inte är tillräckliga får patienten spännas fast med bälte.

>Ett beslut om fastspänning fattas av chefsöverläkaren.  Beslutet gäller högst en timme. Tiden för fastspänningen får förlängas genom nya beslut som gäller under högst en timme i taget. Hälso- och sjukvårdspersonal ska vara närvarande under den tid patienten hålls fastspänd.

>Inspektionen för vård och omsorg ska utan dröjsmål underrättas om patienten hålls fastspänd under en sammanhängande tid som överstiger en timme. Lag (2020:354).

>20 § En patient får hållas avskild från andra patienter endast om det är nödvändigt på grund av att patienten genom aggressivt eller störande beteende allvarligt försvårar vården av de andra patienterna. Ett beslut om avskiljande gäller högst åtta timmar. Tiden för avskiljande får genom ett nytt beslut förlängas med högst åtta timmar.

>Om det finns synnerliga skäl, får ett beslut om avskiljande enligt första stycket avse en bestämd tid som överstiger åtta timmar.

>Chefsöverläkaren beslutar om avskiljande. Om en patient hålls avskild mer än åtta timmar i följd, ska Inspektionen för vård och omsorg utan dröjsmål underrättas om detta. En patient ska under den tid han eller hon hålls avskild stå under fortlöpande uppsikt av hälso- och sjukvårdspersonal.  Lag (2020:354).

>20 a § En patient som är under 18 år får hållas avskild från andra patienter endast om det är nödvändigt på grund av att han eller hon genom aggressivt beteende allvarligt försvårar vården av de andra patienterna och det är uppenbart att andra åtgärder inte är tillräckliga.

>Ett beslut om avskiljande fattas av chefsöverläkaren. Beslutet gäller högst två timmar. Tiden för avskiljandet får förlängas genom nya beslut som gäller under högst två timmar i taget.  Hälso- och sjukvårdspersonal ska hålla patienten under fortlöpande uppsikt under den tid patienten hålls avskild.

>Inspektionen för vård och omsorg ska utan dröjsmål underrättas om patienten hålls avskild under en sammanhängande tid som överstiger två timmar. Lag (2020:354).

>20 b § Chefsöverläkaren får besluta att inskränka en patients rätt att använda elektroniska kommunikationstjänster, om det är nödvändigt med hänsyn till vården eller rehabiliteringen av patienten eller för att undvika att någon annan lider skada.

>Den tekniska utrustning som möjliggör användningen får omhändertas under den tid beslutet gäller. Omhändertagen utrustning skall återlämnas till patienten senast när beslutet om inskränkning upphör att gälla. Lag (2020:354).

>21 § En patient får inte inneha

>1. narkotika, alkoholhaltiga drycker, andra berusningsmedel eller sådana varor som omfattas av lagen (1999:42) om förbud mot vissa hälsofarliga varor,

>2. sådana medel som avses i lagen (1991:1969) om förbud mot vissa dopningsmedel,

>3. injektionssprutor eller kanyler, som kan användas för insprutning i människokroppen,

>4. andra föremål som är särskilt ägnade att användas för missbruk av eller annan befattning med narkotika, eller

>5. annan egendom som kan skada honom eller henne själv eller någon annan eller vara till men för vården eller ordningen på vårdinrättningen.

>Påträffas sådan egendom som avses i första stycket, ska den omhändertas. Lag (2014:522).

>22 § Chefsöverläkaren får besluta att försändelser till en patient får undersökas för kontroll av att de inte innehåller sådan egendom som avses i 21 §. Granskningen av en försändelse får inte avse det skriftliga innehållet i brev eller annan skriftlig handling.

>Om en ankommande försändelse innehåller egendom som inte får innehas enligt 21 §, får egendomen omhändertas.

>22 a § Chefsöverläkaren får besluta att övervaka försändelser från en patient, om det är nödvändigt med hänsyn till vården eller rehabiliteringen av patienten eller för att undvika att någon annan lider skada. För detta ändamål får chefsöverläkaren öppna, ta del av och kvarhålla försändelser från patienten.

>En försändelse från en patient till en svensk myndighet, advokat, patientens offentliga biträde eller ett internationellt organ som har av Sverige erkänd behörighet att ta emot klagomål från enskilda skall vidarebefordras utan föregående granskning. Lag (2006:663).

>22 b § Ett beslut om en inskränkning enligt 20 b § gäller högst två månader eller, om patienten är under 18 år, högst en vecka. Ett beslut om övervakning enligt 22 a § gäller högst två månader.

>När det inte längre finns förutsättningar för ett beslut som avses i första stycket ska chefsöverläkaren genast besluta att inskränkningen eller övervakningen ska upphöra. Frågan om upphörande ska övervägas fortlöpande.

>Tiden för en inskränkning enligt 20 b § får genom nya beslut förlängas med högst två månader i taget eller, om patienten är under 18 år, med högst en vecka i taget. Tiden för övervakning enligt 22 a § får förlängas med högst två månader i taget.

>Inspektionen för vård och omsorg ska utan dröjsmål underrättas om beslut enligt 20 b eller 22 a § och om beslut enligt tredje stycket. Lag (2020:354).

>22 c § Om en patient som är under 18 år har blivit föremål för någon eller några tvångsåtgärder i form av fastspänning, avskiljning eller inskränkning i sin rätt att använda elektroniska kommunikationstjänster vid minst tre tillfällen under vårdperioden, ska Inspektionen för vård och omsorg underrättas om dessa åtgärder. Lag (2020:354).

>23 § Om det är nödvändigt får en patient kroppsvisiteras eller ytligt kroppsbesiktigas för kontroll av att han eller hon inte bär på sig sådan egendom som avses i 21 § eller, när det gäller en patient vars rätt att använda elektroniska kommunikationstjänster är inskränkt, utrustning som avses i 20 b §. Om möjligt skall ett vittne närvara när åtgärden utförs.

>Chefsöverläkaren beslutar om kroppsvisitation och ytlig kroppsbesiktning. Lag (2020:354).

>23 a § Bestämmelserna i 21 och 23 §§ ska gälla alla som vårdas vid en sjukvårdsinrättning eller avdelning för sluten psykiatrisk tvångsvård. Lag (2014:522).

>23 b § Om det är nödvändigt för att säkerheten ska kunna upprätthållas vid en sjukvårdsinrättning eller avdelning för sluten psykiatrisk tvångsvård för vilken en förhöjd säkerhetsklassificering gäller, får vårdgivaren besluta att alla personer som passerar in i inrättningen eller på avdelningen ska kroppsvisiteras (allmän inpasseringskontroll). Syftet med kontrollen ska vara att söka efter föremål som en intagen inte får inneha enligt denna lag eller beslut som har meddelats med stöd av lagen.  Skriftliga meddelanden får inte granskas.

>Kroppsvisitation och undersökning av väskor och andra föremål ska ske genom användande av metalldetektor eller annan liknande anordning eller, om det finns särskilda skäl, på annat sätt.

>Säkerhetskontroll vid domstolsförhandling på sjukvårdsinrättningen beslutas i enlighet med lagen (1981:1064) om säkerhetskontroll i domstol. Lag (2014:522).

>24 § Har narkotika, alkoholhaltiga drycker, andra berusningsmedel, sådana medel som avses i lagen (1991:1969) om förbud mot vissa dopningsmedel eller sådana varor som omfattas av lagen (1999:42) om förbud mot vissa hälsofarliga varor omhändertagits enligt 21 eller 22 § eller har sådan egendom påträffats där patienter intagits för tvångsvård utan att det finns någon känd ägare till egendomen, ska chefsöverläkaren låta förstöra eller sälja egendomen enligt bestämmelserna om beslagtagen egendom i 2 § 1 första stycket lagen (1958:205) om förverkande av alkohol m.m. Detsamma gäller i fråga om injektionssprutor eller kanyler, som kan användas för in- sprutning i människokroppen, och i fråga om andra föremål som är särskilt ägnade att användas för missbruk av eller annan befattning med narkotika.

>Belopp som har erhållits vid försäljning tillfaller staten.  Lag (2019:359).

>25 § Chefsöverläkaren får ge en patient tillstånd att under en viss del av vårdtiden vistas utanför sjukvårdsinrättningens område. Tillståndet får ges för ett visst tillfälle eller för vissa återkommande tillfällen. Tillstånd får ges endast under förutsättning att det står i överensstämmelse med vårdplanen.

>Ett tillstånd att vistas utanför vårdinrättningens område får förenas med sådana villkor som anges i 26 § tredje stycket.

>Chefsöverläkaren får återkalla ett tillstånd som avses i första stycket om förhållandena kräver det. Lag (2008:415).

>25 a § Har upphävts genom lag (2008:415).

>Öppen psykiatrisk tvångsvård

>26 § Den som ges öppen psykiatrisk tvångsvård får vistas utanför sjukvårdsinrättningen.

>Vid beslut om öppen psykiatrisk tvångsvård ska rätten föreskriva de särskilda villkor enligt 3 § första stycket 2 som ska gälla för vården. Rätten får överlämna åt chefsöverläkaren att besluta om dessa villkor. När det finns skäl för det, får rätten återta denna beslutanderätt.

>De särskilda villkoren får avse

>- skyldighet att underkasta sig medicinering eller annan vård eller behandling,

>- skyldighet att hålla kontakt med en viss person,

>- skyldighet att vistas på ett hem eller annan institution för vård eller behandling eller att besöka en vårdcentral eller anlita socialtjänsten,

>- vistelseort, bostad, utbildning eller arbete,

>- förbud mot att använda berusningsmedel,

>- förbud mot att vistas på en viss plats eller att ta kontakt med en viss person, eller

>- annat som är nödvändigt eller följer av vårdplanen. Lag (2008:415).

>26 a § Chefsöverläkaren får besluta att en patient som ges öppen psykiatrisk tvångsvård åter ska ges sluten psykiatrisk tvångsvård om

>1. de förutsättningar som anges i 3 § första stycket 1 och andra stycket är uppfyllda, och

>2. rättens beslut om fortsatt vård inte kan avvaktas med hänsyn till risken för patientens eller annans hälsa eller personliga säkerhet.

>Anser chefsöverläkaren att den slutna psykiatriska tvångsvården bör fortsätta, ska han eller hon senast fyra dagar från dagen för beslutet ansöka hos förvaltningsrätten om medgivande till fortsatt sådan vård. Föreskrifterna i 7 § tredje stycket tillämpas på en sådan ansökan.

>Har en ansökan enligt andra stycket kommit in till förvaltningsrätten, får den slutna psykiatriska tvångsvården fortsätta i avvaktan på förvaltningsrättens beslut.

>Om rätten medger att den slutna psykiatriska tvångsvården ska fortsätta, får den pågå under högst sex månader räknat från den dag förvaltningsrätten meddelar beslut i frågan. I fråga om tvångsvård utöver denna tid tillämpas samma bestämmelser som vid fortsatt tvångsvård enligt 9 §.

>Om chefsöverläkaren inte ansöker om fortsatt sluten psykiatrisk tvångsvård enligt andra stycket eller om rätten avslår chefsöverläkarens ansökan om sådan vård, ska det tidigare beslutet om öppen psykiatrisk tvångsvård kvarstå.  Lag (2009:809).

>Tvångsvårdens upphörande

>27 § När det inte längre finns förutsättningar för tvångsvård, ska chefsöverläkaren genast besluta att tvångsvården ska upphöra. Frågan om tvångsvårdens upphörande ska övervägas fortlöpande. Lag (2008:415).

>28 § Tvångsvården upphör, om inte en ansökan om medgivande till tvångsvård har kommit in till förvaltningsrätten inom den tid som anges i 7, 9 eller 12 §.

>Tvångsvården enligt denna lag upphör också när beslut fattas som föranleder rättspsykiatrisk vård. Föreskrift om övergång till sådan vård finns i 4 § andra stycket lagen (1991:1129) om rättspsykiatrisk vård. Lag (2009:809).

>29 § Har beträffande någon som vårdas enligt denna lag beslut meddelats om

>1. avvisning eller utvisning enligt utlänningslagen (2005:716),

>2. utvisning enligt lagen (1991:572) om särskild utlänningskontroll,

>3. utlämning enligt lagen (1957:668) om utlämning för brott,

>4. överlämnande enligt lagen (2011:1165) om överlämnande från Sverige enligt en nordisk arresteringsorder,

>5. utlämning enligt lagen (1970:375) om utlämning till Danmark, Finland, Island eller Norge för verkställighet av beslut om vård eller behandling,

>6. utlämning enligt lagen (1994:569) om Sveriges samarbete med de internationella tribunalerna för brott mot internationell humanitär rätt,

>7. överlämnande enligt lagen (2002:329) om samarbete med Internationella brottmålsdomstolen,

>8. överlämnande enligt lagen (2003:1156) om överlämnande från Sverige enligt en europeisk arresteringsorder, eller

>9. utlämning enligt lagen (2006:615) om samarbete med Specialdomstolen för Sierra Leone,

>får trots tvångsvården verkställighet av beslutet ske, om det begärs av den myndighet som ska verkställa beslutet och chefsöverläkaren finner att patientens tillstånd tillåter att beslutet verkställs. Tvångsvården upphör i sådant fall när beslutet har verkställts.

>I fråga om en patient som är utlänning upphör tvångsvården vid verkställighet av ett beslut om hemsändande som har meddelats med stöd av 23 kap. 2 § utlänningslagen. Lag (2011:1171).

>Stödperson

>30 § Chefsöverläkaren ska se till att en patient som vårdas enligt denna lag, så snart patientens tillstånd tillåter, genom en individuellt anpassad information upplyses om sin rätt att få en stödperson.

>När patienten begär det, ska en stödperson utses. En stödperson kan utses också i annat fall, om patienten inte motsätter sig det.

>Stödpersonen ska bistå patienten i personliga frågor så länge denne ges tvångsvård enligt denna lag och, om patienten och stödpersonen samtycker till det, även under fyra veckor efter det att tvångsvården har upphört. Stödpersonen har rätt att besöka patienten på vårdinrättningen. Stödpersonen får inte obehörigen röja eller utnyttja vad han eller hon under uppdraget har fått veta om patientens hälsotillstånd eller personliga förhållanden i övrigt.

>Stödpersonen utses av en patientnämnd enligt lagen (2017:372) om stöd vid klagomål mot hälso- och sjukvården.

>Vid en nämnds handläggning av ärenden om stödpersoner tillämpas, utöver vad som i övrigt föreskrivs, följande bestämmelser i förvaltningslagen (2017:900):

>– 10 § om partsinsyn,

>– 11 § om åtgärder om handläggningen försenas,

>– 23 § första och tredje styckena om utredningsansvaret,

>– 24 § om när man får lämna uppgifter muntligt,

>– 25 § om kommunikation,

>– 27 § om dokumentation av uppgifter,

>– 31 § om dokumentation av beslut,

>– 32 § om motivering av beslut,

>– 33 och 34 §§ om underrättelse om innehållet i beslut och hur ett överklagande går till, och

>– 36–39 §§ om rättelse och ändring av beslut.  Lag (2018:798).

>31 § Chefsöverläkaren ska anmäla till en sådan nämnd som avses i 30 § när det kan finnas skäl att utse en stödperson.

>Har en stödperson för patienten inte redan utsetts, ska anmälan alltid göras när

>1. chefsöverläkaren ansöker om medgivande till tvångsvård enligt 7, 12 eller 14 §,

>2. patienten överklagar chefsöverläkarens beslut om intagning enligt 6 b §,

>3. patienten överklagar chefsöverläkarens beslut att avslå en begäran om att tvångsvården ska upphöra.

>I en sådan anmälan ska chefsöverläkaren ange patientens inställning till att få en stödperson. Nämnden ska, om patienten inte har uttryckt en klar uppfattning, kontakta patienten eller vårdpersonal med kännedom om patienten för att få besked om huruvida patienten vill ha en stödperson.

>När tvångsvården av en patient, för vilken stödperson utsetts, har upphört, ska chefsöverläkaren snarast möjligt underrätta nämnden om detta och om huruvida stödpersonens uppdrag fortsätter därefter. Lag (2008:415).

>31 a § Om en patient önskar att stödpersonens uppdrag ska övergå till ett uppdrag som kontaktperson enligt 3 kap. 6 b § socialtjänstlagen (2001:453) när tvångsvården upphört och stödpersonen samtycker till det, ska den nämnd som avses i 30 § underrätta socialnämnden i den kommun där patienten är folkbokförd om patientens önskemål. Lag (2012:780).

>Dagliga aktiviteter och utomhusvistelse

>31 b § En patient som är under 18 år har rätt till dagliga aktiviteter på vårdinrättningen och att vistas utomhus minst en timme varje dag, om inte medicinska skäl talar mot det.  Lag (2020:354).

>Överklagande

>32 § Patienten får till allmän förvaltningsdomstol överklaga chefsöverläkarens beslut om intagning för tvångsvård enligt 6 b, 11 eller 14 §. Ett sådant överklagande ska anses innefatta även en begäran om att tvångsvården ska upphöra.

>Patienten får även överklaga chefsöverläkarens beslut enligt 26 a §. Ett sådant överklagande ska anses innefatta en begäran om att den slutna psykiatriska tvångsvården ska upphöra.

>Innan förvaltningsrätten prövar ett överklagande enligt första eller andra stycket, ska rätten utan dröjsmål förelägga chefsöverläkaren att yttra sig i de hänseenden som anges i 7 § tredje stycket.

>Patienten får till allmän förvaltningsdomstol överklaga ett beslut om inskränkning enligt 20 b § eller om övervakning enligt 22 a §. Lag (2020:354).

>33 § Patienten får hos förvaltningsrätten överklaga ett annat beslut av chefsöverläkaren enligt denna lag som innebär

>1. avslag på en begäran om att tvångsvården ska upphöra,

>2. förordnande enligt 24 § om förstöring eller försäljning av egendom,

>3. avslag på en begäran om tillstånd enligt 25 § att vistas utanför vårdinrättningens område eller meddelande av villkor i samband med en sådan vistelse,

>4. återkallelse enligt 25 § tredje stycket av tillstånd att vistas utanför vårdinrättningens område, eller

>5. meddelande av villkor i samband med öppen psykiatrisk tvångsvård enligt 26 § andra och tredje styckena.

>I övrigt får beslut av chefsöverläkaren enligt denna lag inte överklagas. Chefsöverläkaren får inte överklaga rättens beslut enligt denna lag.

>När ett beslut av chefsöverläkaren överklagas, ska överklagandet ges in till förvaltningsrätten.  Förvaltningsrätten prövar om överklagandet har kommit in i rätt tid. Har överklagandet kommit in för sent, ska förvaltningsrätten avvisa det, om förseningen inte beror på att chefsöverläkaren har lämnat patienten en felaktig underrättelse om hur man överklagar. Överklagandet ska inte avvisas, om det har kommit in till chefsöverläkaren innan tiden för överklagande har gått ut. I ett sådant fall ska chefsöverläkaren omedelbart vidarebefordra överklagandet till förvaltningsrätten. Lag (2009:809).

>Handläggningen i domstol

>34 § Frågor som skall prövas av förvaltningsrätt enligt denna lag prövas av den förvaltningsrätt inom vars domkrets sjukvårdsinrättningen är belägen. Lag (2009:809).

>35 § Mål enligt denna lag skall handläggas skyndsamt. Så snart en ansökan som avses i 28 § har kommit in till förvaltningsrätten, skall rätten pröva om ansökan har kommit in i tid. Har ansökan kommit in för sent, skall rätten skyndsamt underrätta chefsöverläkaren om detta.

>Ett mål hos en förvaltningsrätt skall tas upp till avgörande inom åtta dagar från den dag då ansökan eller överklagandet kom in till förvaltningsrätten. Förvaltningsrätten får förlänga denna tid, om det behövs ytterligare utredning eller om någon annan särskild omständighet gör det nödvändigt.  Förvaltningsrätten får även i fall som avses i 12 § första stycket förlänga den tid inom vilken prövningen skall ske, om chefsöverläkaren gör en ansökan enligt andra stycket i samma paragraf. Föreskrifterna i första och andra meningen gäller inte mål som avses i 33 § första stycket 2.

>Förvaltningsrätten får förordna rörande saken i avvaktan på att målet avgörs. Lag (2009:809).

>36 § I ett mål enligt denna lag skall förvaltningsrätten hålla muntlig förhandling, om det inte är uppenbart obehövligt. Vid prövning som avses i 12 § första stycket skall förvaltningsrätten hålla muntlig förhandling endast om patienten begär det eller om förvaltningsrätten finner skäl för det. Lag (2009:809).

>37 § En muntlig förhandling hålls på sjukvårdsinrättningen, om inte patienten deltar genom ljudöverföring eller ljud- och bildöverföring enligt 14 § förvaltningsprocesslagen (1971:291) eller särskilda skäl talar för något annat. Patienten ska vara närvarande vid förhandlingen, om det är möjligt med hänsyn till patientens psykiska tillstånd. Patientens stödperson har rätt att närvara vid förhandlingen och ska om möjligt underrättas om den. Chefsöverläkaren ska höras vid förhandlingen om det inte är uppenbart obehövligt.

>Om det inte är uppenbart obehövligt ska förvaltningsrätten i ett mål enligt denna lag höra en lämplig sakkunnig vid den muntliga förhandlingen. Vid förhandlingen får den sakkunnige, i syfte att få upplysning om omständigheter som är av betydelse för dennes uppgift, ställa frågor till chefsöverläkaren och patienten.

>Om en patient som har kallats vid vite att inställa sig personligen till en förhandling uteblir, får rätten besluta att patienten ska hämtas till rätten antingen omedelbart eller till en senare dag. Lag (2019:302).

>37 a § Vid sjukvårdsinrättningen ska det finnas den personal, de lokaler och den utrustning som behövs för att en god säkerhet ska kunna tillgodoses vid en muntlig förhandling som hålls där enligt 37 §. Lag (2019:302).

>38 § Vid handläggningen i kammarrätt av mål enligt denna lag skall nämndemän ingå i rätten. Detta gäller dock inte mål som angår enbart en fråga som nämns i 33 § första stycket.

>38 a § Offentligt biträde för den som åtgärden avser ska förordnas i mål hos allmän förvaltningsdomstol, om målet gäller

>1. beslut om intagning för tvångsvård enligt 6 b, 11 eller 14 § och om beslutet har överklagats,

>2. medgivande till fortsatt tvångsvård enligt 7, 9, 12 eller 14 §,

>3. beslut om sluten psykiatrisk tvångsvård enligt 26 a §,

>4. avslag på en begäran om att tvångsvården ska upphöra,

>5. beslut om inskränkning enligt 20 b §, eller

>6. beslut om övervakning enligt 22 a §.

>Offentligt biträde ska dock inte förordnas, om det måste antas att det inte finns något behov av ett biträde. Lag (2020:354).

>39 § Chefsöverläkaren får uppdra åt en erfaren läkare vid sjukvårdsinrättningen med specialistkompetens inom någon av de psykiatriska specialiteterna att fullgöra uppgifter som chefsöverläkaren har enligt denna lag. Om det finns särskilda skäl, får chefsöverläkaren lämna sådant uppdrag åt en annan läkare vid sjukvårdsinrättningen, dock inte när det gäller

>1. beslut enligt 6 b § om intagning,

>2. beslut enligt 11 § om övergång från frivillig vård till tvångsvård,

>3. ansökan enligt 7, 9, 12 eller 14 § om medgivande till att tvångsvården fortsätter,

>4. beslut enligt 17 § tredje stycket om behandlingen,

>5. beslut enligt 19 § andra stycket och 19 a § andra stycket om förlängning av fastspänning,

>6. beslut enligt 20 § andra stycket och 20 a § andra stycket om förlängning av avskiljande,

>7. beslut enligt 20 b § om inskränkning i rätten att använda elektroniska kommunikationstjänster,

>8. beslut enligt 22 a § om övervakning av försändelser,

>9. beslut om upphörande av sådan inskränkning eller övervakning som anges i 7 och 8, eller

>10. beslut eller ansökan om sluten psykiatrisk tvångsvård enligt 26 a §.  Lag (2020:354).

>40 § Regeringen eller den myndighet som regeringen bestämmer får medge undantag från kravet i 4 § på att läkare som utför undersökning för vårdintyg ska vara legitimerad och från kravet i 39 § på specialistkompetens.

>Om regeringen enligt 15 § andra stycket bestämt att vård enligt denna lag får ges på någon annan vårdinrättning än en sådan som drivs av en region, ska regeringen, eller den myndighet som regeringen bestämmer, uppdra åt en erfaren läkare med specialistkompetens inom någon av de psykiatriska specialiteterna att fullgöra de uppgifter som enligt denna lag ankommer på chefsöverläkare. Lag (2019:876).

>41 § Beslut om intagning på en sjukvårdsinrättning samt ansökan enligt 7, 9, 12, 14 eller 26 a § och medgivande med anledning av en sådan ansökan fortsätter att gälla, om patienten överförs till en annan sjukvårdsinrättning utan att beslut har fattats om att tvångsvården ska upphöra. Lag (2008:415).

>42 § Regeringen eller den myndighet som regeringen bestämmer ska för viss tid förordna särskilda sakkunniga att bistå rätten. Lag (2008:415).

>43 § Från en verksamhet där sekretess gäller enligt 25 kap.  1–5 §§ eller 26 kap. 1 § offentlighets- och sekretesslagen (2009:400) ska det utan hinder av sekretessen lämnas ut sådana uppgifter om en patient som behövs för att chefsöverläkarens åligganden enligt denna lag ska kunna fullgöras. Detsamma gäller uppgifter om en patient som behövs för en sakkunnigs uppdrag eller ett yttrande av Socialstyrelsen. Lag (2009:449).

>44 § Om patienten har fyllt 15 år, har han rätt att själv föra sin talan i mål och ärenden enligt denna lag.

>En patient som är yngre bör höras, om det kan vara till nytta för utredningen och det kan antas att patienten inte tar skada av att höras.

>45 § Beslut som meddelas enligt denna lag gäller omedelbart, om inte annat förordnas.

>46 § Vid delgivning med patienten i mål eller ärende enligt denna lag får 34–38 och 47–51 §§ delgivningslagen (2010:1932) inte tillämpas. Lag (2010:1961).

>47 § Om det finns skälig anledning att anta att någon lider av en allvarlig psykisk störning och är farlig för annans personliga säkerhet eller eget liv eller i övrigt behöver omedelbar hjälp, får Polismyndigheten tillfälligt omhänderta honom eller henne i väntan på att hälso- och sjukvårdspersonal kan ge honom eller henne sådan hjälp. Den omhändertagne får föras till en sjukvårdsenhet som kan ge stöd och behandling.

>Polismyndigheten eller, om det gäller en transport av någon i fall som avses i 6, Kriminalvården ska lämna hjälp på begäran av

>1. en läkare som avses i 4 § andra stycket sista meningen för att han eller hon ska kunna genomföra en undersökning för vårdintyg,

>2. en läkare som avses i 4 § andra stycket sista meningen eller av chefsöverläkaren för att föra patienten till en sjukvårdsinrättning sedan vårdintyg har utfärdats,

>3. chefsöverläkaren för att återföra en patient som har lämnat vårdinrättningen utan tillstånd,

>4. chefsöverläkaren för att återföra en patient till vårdinrättningen, om denne inte har återvänt dit sedan tiden för ett tillstånd att vistas utanför inrättningens område har gått ut eller tillståndet har återkallats,

>5. chefsöverläkaren för att återföra en patient till vårdinrättningen, om denne inte har återvänt dit sedan beslut om sluten psykiatrisk tvångsvård har fattats,

>6. chefsöverläkaren för att i annat fall förflytta en patient som är intagen på en sjukvårdsinrättning med stöd av denna lag, eller

>7. Socialstyrelsen för att sända hem en patient som är utländsk medborgare och som vårdas enligt denna lag.

>En begäran enligt andra stycket får göras endast om

>1. det på grund av särskilda omständigheter kan befaras att åtgärden inte kan utföras utan att de särskilda befogenheter som anges i 10 och 10 a §§ polislagen (1984:387) eller, om det gäller en transport som utförs av Kriminalvården, 4 kap.  4 § och 10 § första stycket häkteslagen (2010:611) behöver tillgripas, eller

>2. det annars finns synnerliga skäl.  Lag (2017:134).

>47 a § Kriminalvården ska vid en transport enligt 47 § tillämpa följande bestämmelser i häkteslagen (2010:611):

>– 4 kap. 4 § om kroppsvisitation,

>– 4 kap. 10 § första stycket om användning av fängsel, och

>– 8 kap. 2 a § om möjligheten att i vissa fall begära hjälp av Polismyndigheten. Lag (2017:134).

>47 b § Den som begär hjälp enligt 47 § ska utan hinder av sekretess lämna den verkställande myndigheten de uppgifter om patienten som behövs för planeringen och genomförandet av åtgärden. Lag (2017:134).

>48 § En patient som vårdas med stöd av denna lag skall så snart hans tillstånd medger det genom chefsöverläkarens försorg upplysas om sin rätt

>1. att enligt 32 och 33 §§ överklaga vissa beslut,

>2. att anlita ombud eller biträde och

>3. att enligt 38 a § få offentligt biträde.

>Denna lag skall finnas anslagen inom sjukvårdsinrättningen väl synlig för patienterna. Lag (2000:353).

>49 § Chefsöverläkaren ska fortlöpande till Inspektionen för vård och omsorg lämna uppgifter om åtgärder som har vidtagits enligt denna lag.

>Regeringen eller den myndighet som regeringen bestämmer meddelar föreskrifter om hur uppgiftsskyldigheten enligt första stycket ska fullgöras. Lag (2012:938).


## Resurser

[LPT lagtext](https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/lag-19911128-om-psykiatrisk-tvangsvard_sfs-1991-1128) [@Socialdepartementet1991lpt]

[SOSFS 2008:18 Socialstyrelsens föreskrifter och allmänna råd om psykiatrisk tvångsvård och rättspsykiatrisk vård](https://www.socialstyrelsen.se/regler-och-riktlinjer/foreskrifter-och-allmanna-rad/konsoliderade-foreskrifter/200818-om-psykiatrisk-tvangsvard-och-rattspsykiatriskvard/) [@Socialstyrelsen2008lptrad]

[Se Regeringens proposition 1990/91:58 om psykiatrisk tvångsvård mm (resonemang om allvarlig främst s82-102)](https://www.riksdagen.se/sv/dokument-lagar/dokument/proposition/om-psykiatrisk-tvangsvard-mm_GE0358) [@Regeringen1990lptprop] 

[JURIS Online (prenumeration krävs)](https://secure.webforum.com/orebropsyk/start/)
