# Psykos {#psychosis}

Kan ej skilja på inre och yttre.

Psykos inbegriper (enskilt eller i någonn kombination):

- Hallucinationer
- Vanföreställningar
- Desorganiserat beteende
- Desorganiserat tal

Hallucinationer: Sensoriska upplevelser som saknar yttre stimulus. Vid psykos saknas insikt om att yttre orsak inte finns.

Vanföreställningar: Helt osannolika föreställningar som personen är starkt övertygad om ävan när motsatsen bevisas. Kan beskrivas som persekutoriska, grandiosa, grandiosa, erotomana, religiösa.

Desorganiserat beteende: Udda rörelser, kroppspositioner, katatoni.

Desorganiserat tal: Ologiskt innehåll, obegriplighet, tangentialitet, neologismer, klangassociationer, ordsallad, ekolali mm.

Biologiska, psykosociala, och kulturella faktorer kan bidra.

I psykiatrisk diagnostik används tex duration (tex >6 månader vid schizofreni) och relation till affektiva episoder (endast inom- eller finns även utanför) för att indela psykoser i olika diagnoser.

[@Lieberman2018]

Överskott på dopaminerg och glutamaterg signalering kan vara en biologisk process som orsakar psykos. Kannabinoidreceptorer och serotonin (psykedelika) kan också vara inblandade.

Psykologiska modeller av psykos inbegriper bla att psykos kan vara en följd av nedsatt förmåga att processa otydliga stimuli samt en tendens att ta ett beslut på basen av mindre information[@Garety1991;@Garety2007].

Huntingtons sjukdom kan ge psykos (10%), ofta även depression, kognitiv nedsättning, irritabilitet.

## Differentialdiagnostik

| Orsak               | Debutålder             | Förlopp  | Funktion | Not                            | Livstid |
|---------------------|------------------------|----------|----------|--------------------------------|---------|
| Akut psykos         |                        |          |          |                                | 0.05    |
| Schizofreni         | 15-30                  | Smygande |          |                                | 0.3-0.9 |
| Schizofreniform     |                        |          |          |                                | 0.07    |
| Schizoaffektiv      |                        | Smygande |          |                                | 0.3     |
| Vanföreställnsyndr  | Medelålder             |          |          |                                | 0.18    |
| Depression m psykos | 15-30                  |          |          |                                | 0.33    |
| Bipolär m psykos    | 15-30                  |          |          |                                | 0.12    |
| Post partum         |                        |          |          | Oftast bipolärt syndrom        | 0.07    |
| Neurodegenerativ    | Äldre                  |          |          |                                |         |
| Toxisk              |                        | Snabbt   | Snabb    |                                |         |
| Medicinskt tilst    |                        | Snabbt   | Snabb    |                                |         |
| Delirium            |                        |          |          | Ouppmärksamhet                 |         |
| Demens              |                        |          |          | Kognitiv defekt                |         |
| SLE                 |                        |          |          | 30% NMDAR-ak                   |         |
| Ovariecancer        |                        |          |          | NMDAR-ak                       |         |
| Tertiärsyfilis      |                        |          |          |                                |         |
| Epilepsi            |                        |          |          |                                |         |
| Limbisk encefalit   | Paraneoplastisk, viral | Subakut  |          | HSV1, VZV, mm. Sänkt medv grad |         |
| Wernicke-Korsakoff  |                        |          |          |                                |         |

Toxisk/medicinsk: a history of headaches, seizures, or visual, olfactory, or tactile hallucinations; and an absence of a family history of psychotic disorders

Visuella hallucinationer eller ändrad medvetandegrad kan tala för sekundär orsak.

Schizofreni och schizoaffektid sjukdomsförlopp: premorbid, prodromal, syndromal, progressive, and chronic stages 

Hereditet: Schizofreni och bipolär m psykos har vardera konkordans 50% hos enäggstvillingar. Förstagraddsläktingar till person med psykos har 10-15 ggr högre prevalens.

Vid epilepsi är förekomsten av schzofreni dubblerad. Andra type av psykoser förekommer och brukar delas in efter tidsrelationen till epileptiska anfall (iktal-, postiktal- och interiktal psykos). Psykos är vanligare vid temporallobsepilepsi (prevalens 10%)[@Maguire2018].

>"In postictal psychosis, as in this case, there is lucid period of between a few hours and a few days, followed by insomnia and agitation, leading to psychosis. The psychotic symptoms are typi- cally positive, with prominent persecutory delusions, and often a strong affective component. Patients may be aggressive with directed violence.18 19 The symp- toms generally last a few (mean 9–10) days, although are sometimes more protracted, lasting weeks to months and requiring psychotropic medication."[@Maguire2018]

>Psychotic symptoms sometimes form part of the seizure (ictal psychosis). They are of sudden onset, brief and abort as the seizure aborts. Ictal psychosis may occur in the context of non-convulsive status epilep- ticus where patients may show bizarre behaviour and thought incoherence, with or without loss of aware- ness. Delusions and hallucinations are less common than in postictal psychosis; patients may show other seizure features, such as motor or orobuccal automa- tisms as part of temporal lobe epilepsy.[@Maguire2018]

>A more difficult challenge for clinicians is to distin- guish interictal psychosis from schizophrenia. Interictal psychosis can manifest as brief or chronic forms. The chronic forms of interictal psychosis may closely resemble schizophrenia; however, several features help to distinguish the two. Schizophrenia often begins in young adulthood. In contrast, interictal psychosis manifests predomi- nantly with the positive psychotic symptoms of delusions and hallucinations, which are less likely to be third-person auditory, and have better preserved personality traits and no negative symptoms. The psychosis can last days to months but may be more protracted. It can be very difficult to distinguish between interictal psychosis and postictal psychosis and in many patients these coexist. [@Maguire2018]

Se [@Skikic2020] för kliniskt vägledd diagnostik.

## Tankestörning

Kan indelas i störning av tankeförlopp (formell tankestörning) respektive -innehåll (vanföreställingar).

### Tankeförlopp (formella tankestörningar)

<!-- Formell tankestörning är desorganiserat tänkande, vilket ger avvikelser i hur personen uttrycker sig i tal och skrift. -->

Formell tankestörning innebär en oförmåga att vidmakthålla ett sammanhängande samtal och avspeglar störning i tankarnas organisation och uttryck (hur de formuleras) snarare än deras innehåll.

<!-- - Avvikelse kan övergripande beskrivas som stört eller desorganiserat tänkande. -->
<!-- - Beskriv kvantitet, tempo/flöde, logiskt sammanhang. -->

#### Typer av stört tankeförlopp

De kan indelas i positiva- och negativa, samt objektiva och subjektiva (där de senare måste efterfrågas).

**Positiva:** Tex urspårning, uppluckring av associationer, neologismer och konstlat tal [stilted speech].

**Negativa:** Minskad produktion av tal eller tankar. Tex tankefattighet, långsamt tänkande.

**Subjektiva:**

- Positiva: Tex pressure of thoughts, thought interference

- Negativa:  Tex inhibited thinking, dysfunction of thought initiative

<!-- disorganization, emptiness, and incoherence. -->

Tabell: Karakteristiska formella tankestörningar

| Pos/Neg | Obj/Subj | Karakteristiskt                                                                                  | Beskrivande    |
|---------|----------|--------------------------------------------------------------------------------------------------|----------------|
| Pos     | Obj      | derailment and crosstalk                                                                         | Desorganiserad |
| Pos     | Subj     | pressure/rush of thought and thought interference                                                |                |
| Neg     | Obj      | poverty of speech, slowed thinking and concretism                                                | Tomhet         |
| Neg     | Subj     | poverty of thought, inhibited thinking, and dysfunction of thought initiative and intentionality | Introspektiv   |

>Objective positive FTD is highest in mania and objective negative FTD is highest in schizophrenia and major depressive disorder[@Kircher2018].

>Chronic positive FTD is a diagnostic marker for schizophrenia, and negative FTD in schizophrenia is associated with poor social functioning and outcome[@Kircher2018].

>FTDs in individuals with schizophrenia have been consistently associated with cognitive impairment in executive functioning, attention, verbal fluency, and working memory[@Kircher2018].

Dimensioner av formell tankesörning[@Stein2022;@Kircher2018;@Kircher2014]. Supplementet i ref [@Kircher2014] innehåller definitioner. Se även "Scale for the assessment of thought, language, and communication (TLC)"[@Andreasen1986] för beskrivning av vissa tankestörningar.

<!-- Förenkling: Beskriv ökad/minskad tal/tankeproduktion (=tempo?). Grad av urspårning/uppluckring i associationer. Förbisvar. Fråga om Tanketrängsel, rusande tankar, inhiberat tänkande. Om ovanligare yttringar som tex neologismer eller konstlat tal förekommer kommenteras det. -->

<!-- "Normalt taltempo och tankeförlopp." -->

<!-- "Ökat taltempo. Måttligt uppluckrade associationer. Beskriver tanketrängsel. En del förbisvar." -->

<!-- En del av termerna är relaterade med varandra?. Några begrepp som kanske kan ses som grader på en skala: Omständlighet < tangentialitet < idéflykt < uppluckrade associationer < ordsallad. -->

Terminologin är inte helt konsekvent i olika källor, men nedan beskrivs ett urval.

- Tankefattighet (poverty of thought/poverty of speech/alogia): Minskad mängd tal eller fattigt innehåll (utarmat/innehållslöst tal, stereotypier).
- Inhiberat tänkande: Tankarna tycks flöda långsamt med få associationer.
- Blockering/tankestopp/tankespärr(thought blocking, speech blocking): Plötsligt, omotiverat uppehåll mitt i en tankekedja (kan eller kan inte ta upp tråden igen). Enligt DSM-IV skall tankestopp anses föreligga enbart om personen spontant berättar att tankarna försvann, eller om han eller hon anger detta som skäl till sin tystnad på direkt fråga från intervjuaren. Observera att man normalt kan bli blockerad då man pratar om ett ångestladdat ämne, eller vid uttalad trötthet.
- Ökat talflöde/forcerat talflöde (Pressure of speech, pressured speech, rapid speech): Oupphörligt, snabbt tal utan pauser. Ibland höjd röst och med onödiga ord. Svårt att avbyta. Fortsätter tala även när ingen lyssnar. 
- Perseveration: Ihärdig repetition av ord ("Det är fint att vara här i Örebro, Örebro, Örebro") eller idéer även när en annan person försöker byta ämne. Har svårt att avbryta en tankegång. Kan också yttra sig i att man ger samma svar på olika frågor, tex: "Heter du Jhonny?" "Ja."; "Är du på sjukhuset?" "Ja"; "Är du ett bord", "Ja".
- Omständlighet (circumstantiality): Klarar inte att svara på frågor utan att ge många irrelevanta detaljer och utvikningar men klarar sedan att återvända till ämnet i stort. 
- Tangentialitet (tangentiality): Avviker från ämnet utan att kunna återvända eller ge den efterfrågade informationen. Variation: tangential circumstantial (being vague, ie, "beating around the bush")
- Tankeflykt/idéflykt (flight of ideas, change topics): Snabb tankeström med tvära kast från ett ämne till ett annat, med svårförståeliga kopplingar (samma tema, poetiska associationer, rim, ordlekar) mellan idéerna. Olika grad, från lätt uppluckrade associationer till osammanhängande tal.
- Associationsrikedom (derailment, knight's move thinking): Extrem irrelevans. Tankarna/talet rör sig från ämnet till ett annat ämne som är orelaterat eller mycket vagt relaterat.
- Uppluckrade associationer: Byter omotiverat spår från den ena meningen till den andra, utan någon som helst eller mycket långsökt koppling.
- Inkoherens/splittring/ordsallad (incoherence, schizaphasia): Obegripligt tal eftersom personen byter spår inom själva meningsbyggnaden. Enskilda ord är riktiga men kombineras på ett vis som gör talet obegripligt. Ordsallad beskriver en hög grad av splittring.
- Distraherat tal (Distractible speech): During mid speech, the subject is changed in response to an external stimulus. e.g. "Then I left San Francisco and moved to... where did you get that tie?"
- Klangassociationer (clanging, clang associations, rhyming words, word plays, idiosynchratic associations): En svårare form av tankeflykt där tankegången hänger ihop genom ljud snarare än innehåll. Ordvalet kan styras av ljudlikhet, tex med överdrivet rimmande eller ordlekar.
- Loss of goal – Failure to follow a train of thought to a natural conclusion. e.g. "Why does my computer keep crashing?", "Well, you live in a stucco house, so the pair of scissors needs to be in another drawer."
- Neologismer (neologisms): Formar nyord (som inte har någon allmänt accepterad betydelse), exempelvis genom att sätta ihop två existerande ord, eller använder existerande ord på ett excentriskt vis.
- Ekolali (echolalia): Upprepning av en annas ord. Variant: Palilalia (upprepning av sina egna ord).
- Parafasi (paraphasia): Språkstörning som består i oavsiktlig förväxling av ord (semantic paraphasia, "I slipped on the coat, on the ice I mean, and broke my book.") och enskilda ljud (phonemic paraphasia, "I slipped on the lice and broke my arm."). 
- Förbisvar: Ger ett felaktigt svar på en fråga trots att frågan uppfattats. Ex: "Är det något som tynger dig?" "Ja, bordet är tungt".
- Andra: punning (talking in riddles), verbigeration (the constant or obsessive repetition of meaningless words or phrases), overinclusion (overgeneralization and inability to maintain boundaries in categories), racing (rapid thoughts), self-reference (patient repeatedly and inappropriately refers back to self. e.g. "What's the time?", "It's 7 o'clock. That's my problem."), Word approximations (old words used in a new and unconventional way. e.g. "His boss was a seeover."), Illogicality (Conclusions are reached that do not follow logically (non-sequiturs or faulty inferences). e.g. "Do you think this will fit in the box?" draws a reply like "Well duh; it's brown, isn't it?"), Stilted speech (Speech characterized by the use of words or phrases that are flowery, excessive, and pompous.[9] e.g. "The attorney comported himself indecorously."), Evasive interaction (Attempts to express ideas and/or feelings about another individual come out as evasive or in a diluted form, e.g.: "I... er ah... you are uh... I think you have... uh-- acceptable erm... uh... hair.")

Tabell: Formella tankestörningar[@Kircher2018] med % förekomst i en studie där deltagarna hade Depression (n = 63),	Schizophrenia (n = 63),	Mania (n = 20), eller var Healthy (n = 64)

```{r } 
#| label: tald 

dta <- fread("../notes/formal_thought_disorder.csv")
dta <- as.data.table(lapply(dta, function(x){gsub("\n", "", x)}))
dta[, percent := as.numeric(percent)]

setorder(dta, -percent)

## N=192?

knitr::kable(dta[, .(tald_item, percent)])

``` 

 

#### Tolkning

| Tankestörning      | Typiskt vid                                 |
|--------------------|---------------------------------------------|
| Idéflykt           | Mani                                        |
| Inhiberat tänkande | Depression, Schizofreni, demens             |
| Perseveration      | Demens                                      |
| Omständlighet      | Schizofreni, Ångest, personlighetsstörining |
| Tankefattighet     | Schizofreni                                 |
| Tankeblockering    | Schizofreni                                 |
| Klangassociationer | Mani, Schizofreni                           |
| Ekolali            | Tourette                                    |
| Neologismer        | Schizofreni, mani                           |

<!-- - Flight of ideas is typical of mania. Conversely, patients with depression may have retarded or inhibited thinking. Poverty of thought is one of the negative symptoms of schizophrenia, and might also be a feature of severe depression or dementia. A patient with dementia might also experience thought perseveration. Formal thought disorder is a common feature of schizophrenia. Circumstantial thinking might be observed in anxiety disorders or certain kinds of personality disorders. -->

<!-- - Störningar i tankeförlopp kan tala för psykos. psykotiska tankestörningar: omotiverade uppehåll i talet? fråga efter tankestopp, tankepåsättning, tankeutbredning, tankedetraktion, tanketrängsel -->

<!-- - Alogia (also poverty of speech) – A poverty of speech, either in amount or content; it can occur as a negative symptom of schizophrenia. -->

<!-- - Blocking: This is a type of formal thought disorder that can be seen in schizophrenia.[1] -->

<!-- - Clanging or Clang association – It is most commonly seen in bipolar affective disorder (manic phase), although it is often observed in patients with primary psychoses, namely schizophrenia and schizoaffective disorder. -->

<!-- - Perseveration can include palilalia and logoclonia, and can be an indication of organic brain disease such as Parkinson's. Perseveration  Kan ses vid vissa psykotiska tillstånd, vid desorientering samt hos vissa epileptiker. Förekommer ibland hos deprimerade patienter i form av ett svåravledbart ältande.   -->

<!-- - Idéflykt: It is most characteristic of the manic phase of bipolar illness. -->

<!-- - Ekolali: This can be a symptom of Tourette's Syndrome. -->

<!-- - Neologismer: psykos, ffa scizofreni. Mani? -->

- Övergående depersonalisation är ett vanligt fenomen (som uppges kunna förekomma hos 50 % av befolkningen), speciellt hos barn och ungdomar men även hos vuxna när de reser till nya och okända platser, i samband med uttröttning eller starka känsloreaktioner.

- Tanketrängsel: Tanketrängsel vid schizofreni visar bara en yttre likhet med den tankeflykt / idéflykt som förekommer vid den maniska fasen i manodepressiva psykoser. Vid schizofreni sprängs främmande tankefragment in i de logiska tankesekvenserna.

- Ökat talflöde: Förekommer i första hand vid hypomana- och maniska tillstånd, men kan observeras även vid påverkan av t ex centralstimulerande medel och vid psykotiska sjukdomstillstånd.

### Tankeinnehåll (Innehållsmässiga tankestörningar)

- Avspeglar personens föreställingar och tolkning av stimuli. 
- Undersök intensitet, vilken vikt patienten lägger vid tankarna, känslor som är förknippade med tankarna, om tankarna upplevs vara under ens egen kontroll, graden av övertygelse som är förknippad med tankarna.
- Disorders of thought content reflect the patient’s ideas, beliefs, and interpretations of stimuli. Delusions, the most obvious example

#### Vanföreställningar

- Övervärdiga idéer: a false belief that is held with conviction but not with delusional intensity. Hypochondriasis is an overvalued idea that one is suffering from an illness, dysmorphophobia is an overvalued idea that a part of one's body is abnormal, and people with anorexia nervosa may have an overvalued idea of being thin.
- En vanföreställning låter sig ej korrigeras, trots att övertygelsen är uppenbart felaktig och personens begåvning och utbildning bör göra det möjligt för honom att inse detta. 

<!-- "a false, unshakeable idea or belief which is out of keeping with the patient's educational, cultural and social background ... held with extraordinary conviction and subjective certainty". The patient's delusions may be described as persecutory or paranoid delusions, delusions of reference, grandiose delusions, erotomanic delusions, delusional jealousy or delusional misidentification. Delusions may be described as mood-congruent (the delusional content in keeping with the mood), typical of manic or depressive psychoses, or mood-incongruent (delusional content not in keeping with the mood) which are more typical of schizophrenia. Delusions of control, or passivity experiences (in which the individual has the experience of the mind or body being under the influence or control of some kind of external force or agency), are typical of schizophrenia. Examples of this include experiences of thought withdrawal, thought insertion, thought broadcasting, and somatic passivity. Schneiderian first rank symptoms are a set of delusions and hallucinations which have been said to be highly suggestive of a diagnosis of schizophrenia. Delusions of guilt, delusions of poverty, and nihilistic delusions (belief that one has no mind or is already dead) are typical of depressive psychoses. -->

- Bisarr vanföreställning: Fullkomligt otroligt. Man behöver med andra ord inte fundera över om personen kan ha rätt i det han tror.
- Icke-bisarr vanföreställning: Vanföreställning som hypotetiskt skulle kunna överensstämma med verkligheten. Ex: Förföljd av polisen.
- Tankedetraktion: Tankedetraktion är en form av innehållsstörning med vanföreställningar, som innebär att den drabbade tror att de egna tankarna blivit borttagna ur huvudet till exempel av en utomjordisk makt eller av någon människa
- Påverkansupplevelser/tankepåsättning (thought pressure, pressure of ideas, thought insertion, intrusive thoughts, thought control): Föreställning att ens tankar/känslor/handlingar kommer som ett tvång utifrån.
- Tanketrängsel: Flera tankar med olika innehåll och inriktning tränger sig på i medvetandet samtidigt.
- Tankeutbredning/tankeeko: Upplevelse av att de egna tankarna samtidigt tänks av någon annan, likt ett eko eller en radiosändning.
- Hänsyftningsidéer: Personen har tankar om att tillfälligheter och yttre händelser har en speciell och ovanlig betydelse som är specifik för just honom eller henne. Personen känner till exempel att det som skrivs i tidningarna eller diskuteras i radion i själva verket syftar på honom eller henne. 
- Depressiva vanföreställningar Handlar om otillräcklighet, skuld, sjukdom, död, nihilism eller bestraffning. Kan inkludera förföljelseparanoia om denna förknippas med självnedvärderande teman som t ex välförtjänt straff. Exempel på depressiva vanföreställningar är
- Grandiosa / megalomana vanföreställningar Handlar om uppblåst självbild, makt, kunskaper, identitet eller ett speciellt förhållande till gudar eller kända personer. 
- Magiskt tänkande: En felaktig föreställning om att ens tankar, ord eller handlingar kan förorsaka eller förhindra ett speciellt händelseförlopp på ett sätt som inte följer allmänt accepterade principer om orsak och verkan.
- Förföljelseparanoia: Vanföreställningar där huvudtemat är att personen (eller någon närstående) attackeras, trakasseras, luras, förföljs eller motarbetas.  
- Svartsjukeparanoia: Vanföreställningar om att ens sexuella partner är otrogen. Vanligt vid alkoholberoende.  
- Erotomani: Vanföreställning om att en annan person, vanligtvis med högre status, är förälskad i personen.  
- Somatiska vanföreställningar: Vanföreställningar som gäller kroppens utseende eller funktioner. Dessa har ofta en depressiv prägel
- Dysmorfofobi: Tillstånd som strikt sett inte når upp till vanföreställningsstatus. Orealistisk upplevelse av att någonting i utseendet är ”fel”. Objektivt finner man inget anmärkningsvärt i patientens utseende. 
- Dysmorfoparanoia: Vanföreställningar där personen kan vara helt fixerad vid sin upplevda deformitet och invalidiserad av sin upplevelse.


## Akut psykos

ICD: Akut och övergående psykos
DSM: Brief psychotic disorder

Psykotiska symtom under 1 dag till 1 månad, utan annan orsak (stressor kan ingå i ICD-definitionen).

<!-- Orsaker, principiellt: -->

<!-- - Biologiska (neurologiska, droger, medicinska, psykiatriska) -->
<!-- - Psykologiska (stress) -->
<!-- - Sociokulturella -->

Psychiatric causes include schizophrenia, schizoaffective disorder, bipolar disorder, major depressive disorder, delusional disorder, schizophreniform disorder, brief psychotic disorder, and postpartum psychosis

Kartlägg ärftlighet, sociala faktorer, missbruk, drogbruk, livshändelser, 

Autoimmun encefalit: Kramper, katatoni, autonom instabilitet, hyperkinesi.

### Provtagning

- Drogscreening
- Uteslut infektion: Temp, blodstatus, urinsticka, ev lungröntgen, ev blododling, ev LP.
- Uteslut metabol orsak: Krea (uremi), glukos, leverstatus (leversvikt, Wilsons), elektrolyter inkl kalcium (Addison, cushing, hyperpara)
- Endokrint: Thyroideastatus
- Uteslut autoimmun orsak: ANA (SLE),
- Övrigt: HIV, syfilis, (ceruloplasmin). Ev EEG (EP), läkemedelskonc, tungmetaller (om misstänkt exponering i hem eller yrke)
- B12, folat, Mg, (Vit A, B1, B3?) om undernärd eller vegan.
- Alkoholmarkör?
- MR: Demyeliniserande sjukdom, stroke, hjärntumör. Screening endast vid neurologiska fynd, eller ålder >45.
- Genetisk testning om ålder <13 å.

I nationella vårdprogrammet anges samtliga undersökningar under "kan utföras" [Länk](https://www.vardochinsats.se/schizofreni-och-liknande-tillstaand/kartlaeggning-och-utredning/initial-utredning-schizofreni-och-schizofreniliknande-tillstaand/).

Symtom som kan föranleda utvidgad utredning (tex MR, EEG, paraneoplastisk panel): Avvikande nervstatus (tex nystagmus, afasi, motoriska bortfall, myoklonus), medvetandesänkning, frånvaroattacker, konfusion, huvudvärk, illamående/kräkning, inkontinens, feber

**EEG:** "EEG uppvisade oacceptabelt låg diagnostisk säkerhet. Det finns inget stöd för EEG som diagnosmetod vid psykotisk sjukdom, eller för att utesluta annan cerebral sjukdom av organisk genes, hos patienter med förstagångsinsjuknande i psykotiska symtom.  Otillräckligt vetenskapligt underlag" [Länk](https://mellanarkiv-offentlig.vgregion.se/alfresco/s/archive/stream/public/v1/source/available/sofia/su4372-1728378332-280/surrogate/2012_47%20HTA-rapport%20EEG%20as%20a%20diagnostic%20tool%20in%20patients%20with%20first%20episode%20psychosis.pdf). Vid katatoni där orsaken är oklar kan EEG ha ett värde för att skilja mellan organisk- och ickeorganisk orsak[@Hosseini2023]. EEG kan övervägas om "Staring spells, episodic loss of consciousness, myoclonic movements/rigidity"[@Skikic2020]

**Ceruloplasmin:** Wilsons sjukdom är ovanlig, men många får psykiatriska symtom. Kayser-Fleischer ring (gyllenbrun, kan vara grön, röd, blå) föreligger hos 95%, så frånvaro av detta torde kunna göra mäting av ceruloplasmin onödig. Misstänk vid: Psychiatric disease with signs of hepatic or neurological disease? "Kayser-Fleischer rings may not be easily visible on routine examination. In the initial stages, a slit lamp is generally necessary to identify the rings. However, visibility with the naked eye becomes possible as the disease progresses, especially in patients with lightly pigmented irises and severe copper overload. Therefore, a slit-lamp examination is imperative for diagnosis."[@Pandey2024]

**Syfilis:** Neurosyfilis[@Ropper2019]. Kan ge psykiatriska symtom som första tecken.

## Behandling

"Numerous agents have been examined as adjunctive treatments to antipsy- chotic medications, but their effects are modest, and evidence for their efficacy is limited. 35 The same is true for combinations of conventional antipsychotic drugs.

ECT is effective for catatonia and for mood disorders with psychotic symptoms and is indicated in patients with schizophrenia or schizoaffective disorders when symptoms are unresponsive to antipsychotic medications.  One promising application of neuromodula- tion is for control of psychotic auditory or verbal hallucinations. Initial studies were performed with TMS applied over the region of the left temporal lobe that overlies the auditory cortex. 36 More recently, tDCS applied over the region of the auditory cortex has led to reductions in hallu- cinations and in persistent negative symptoms of schizophrenia, such as apathy and social with- drawal.

Cognitive and behavioral rehabilitation has been used in the treatment of idiopathic psychotic disorders — in particular, schizophrenia.39 The most widely studied of these techniques is social skills training, in which patients are instructed, after stabilization of their acute psychotic symp- toms, about appropriate modes of behavior and communication with others and about practical life skills that may have been impaired by psy- chotic disorders. Another psychosocial treatment with strong empirical support is family psycho- education, which enables family members to help support the patient’s recovery.

Cognitive behavioral therapy (CBT), a treatment originally developed for mood and anxiety disorders, may also be useful for psychotic symp- toms. Specific CBT approaches used in treating patients with schizophrenia include cognitive restructuring (i.e., engaging patients to change beliefs about their hallucinations and delusions), behavioral exposure to stimuli that trigger psy- chotic symptoms to enhance reality testing, self- monitoring, and graded coping skills. CBT in patients with schizophrenia can also help to re- duce the distress caused by hallucinations or delusional beliefs."

## Behandling av akut försämring vid schizofreni

Antipsykotiska medel har viss men måttlig effekt vid akut försämring (SMD 0.45 för positiva symtom; 0.35, för negativa symtom, livskvalitet och fungktion)[@Leucht2017]. 

<!-- The analysis included 167 double-blind randomized controlled trials with 28,102 mainly chronic participants. The standardized mean difference (SMD) for overall efficacy was 0.47 (95% credible interval 0.42, 0.51), but accounting for small-trial effects and publication bias reduced the SMD to 0.38. At least a “minimal” response occurred in 51% of the antipsychotic group versus 30% in the placebo group, and 23% versus 14% had a “good” response. Positive symptoms (SMD 0.45) improved more than negative symptoms (SMD 0.35) and depression (SMD 0.27). Quality of life (SMD 0.35) and functioning (SMD 0.34) improved even in the short term. Antipsychotics differed substantially in side effects. Of the response predictors  -->
 


## Särskilda typer av psykos

Capgras

- Vanföreställning om att en välkänd nära person har bytts ut mot en bedragare
- Organisk orsak (lewykroppsdemens, EP, stroke, B12-brist, hepatisk encefalopati, diabetes, hypothyroidism) i 25% av fallen

Post parum psykos

- Ofta bipolärt syndrom.

### Lewykroppsdemens och parkinson med demens

Konfusion, parkinsonism, synhallucinationer, påminner om parkinson med demens. Den mest vanliga demenssjukdomen efter alzheimers. Prevalens ca 15% av demenspatienter i kliniska material, i patologiska studier 20%.  Ofta fluktuerande symtom vilket kan föranleda att man söker akut

#### Lewy body demens – Identifiera de 4 kärntecken

1. Fluktuerande kognition/uppmärksamhet och vakenhet(uttalad trötthet, episodisk konfusion, vilda drömmar, mycket trött, sover >2 timmar på dagen)

- Vanligt med dagar (till veckor) där den kognitiva funktionen är avsevärt bättre
- Dvs Slöhet samt kognitiv dysfunktion. Orsakad av autonom dysfunktion med cirkulationsproblem

2. Återkommande synhallucinationer(synhallucinationer med insikt, brukar vara välformade och detaljerade. dubletter av maken/makan = capgras)

- Sällan auditiva hallucinationer

3. REM-sömnstörning (vilda drömmar, kan föregå de kognitiva symptomen).

- Agerar ut drömmarna: Endast viókalisering är normalt, men sparkar, viftar, ramlar ur sängen. Kan vara tidigt tecken.

4. Minst ett av parkinsonismens kardinalsymptom (bradykinesi, vilotremor, rigiditet). Bradykinesi är det viktigaste symtomet vid parkinsonism.

- Oftast bilateralt symmetriskt (jfr Mb Parkinson ofta ensidig första året)

#### Lewy body demens – stödjande kliniska tecken

(behövs inte för diagnos)

- Svår neuroleptika känslighet
- Postural instabilitet. Upprepade fall
- Svimning eller övergående episoder med okontaktbarhet
- Svår autonom dysfunktion (förstoppning, ortostatisk hypotension, urininkontinens
- Hypersomni
- Hypoosmi
- Hallucinationer av andra modaliteter 
- Systematiserade vanföreställningar (cotard)
- Apati, oro, depression

Stödjande biomarkörer

- Relativt bevarade mediala temporallober på CT/MR
- Generellt lågt upptag på SPECT/PET
perfusion/metabolism scan med reducerad occipital
aktivitet, ”cingulate island sign” på FDG-PET.
- DaT(dopamine transporter) SCAN, För diff diagn mellan DLB och AD
- Uttalad långsam EEG aktivitet posteriort med periodiska fluktuationer i prealpha/theta området.

#### Lewy body demens – kriterier, tolkning

- Sannolik (probable) DLB: 2 eller fler kärntecken eller 1 kärntecken + 1 eller fler indikativa biomarkörer
- Möjlig (possible) DLB: 1 eller fler kärntecken eller 1 eller fler indikativa biomarkörer

<!-- *** Medicinering: (för detaljer se sist) -->

<!-- - Förstahands behandling: Acetylkolinesterashämmare (förbättrar även hallucinos) -->
<!-- - RCT studie: Rivastigmine -->
<!-- - Parkinsonismen – L-dopa -->
<!-- - Drömsömnen – Mirtazapin (upp till 45 mg, hjälper mot rem-sömnstörningar), Klonazepam, Melatonin -->
<!-- - Hallucinationer – öka kolinesterashämmare, (Quetiapin?, Klozapin?) -->
<!-- - Ortostatism – Stödstrumpor, Midodrine -->
<!-- - Depression – SNRI, Mirtazapin -->
<!-- - Nokturi - ? Behandling:EJ antikolinergika (Detrusitol, Emselex, -->
<!-- Vesicare) -->
<!-- Inkontinenshjälpmedel. Minskad dryck, fr a kaffe, öl till -->
<!-- kvällen/natten. -->

<!-- https://www.bmj.com/content/374/bmj.n1779/rr-4 -->
