### make a listr of value-replacement pairs
spellList <- list(
    'Reiationship'= "Relationship",
    'Prevaience'= "Prevalence",
    'Deveiopment' = "Development",
    'medicai' = "medical",
    'Reiated' = "Related",
    'Risic' = "Risk",
    'icnown' = "known",
    'iVlaricers' = "Markers",
    'lUliid' = "Mild",
    'lUloderate' = "Moderate",
    'Cuiture' = "Culture",
    'Fieid' = "Field",
    'Triais' = "Trials",
    'Fiuency' = "Fluency",
    'commimication' = "communication",
    'foimdational' = "foundational",
    's e c tio n' = "section",
    'comotbid' = "comorbid",    
    'abihty' = "ability",
    'Witli' = "With",
    ## Note: One-letter replacements should come at the end so that the above work
    ' ̂' = "",
    '(-){2,}' = "",
    '(_){2,}' = "",
    '(_̂){1,}' = "",
    'iVl' = "M",
    'lUl' = "M"
)
